### ISSUE TITLE
unable to style header

### ISSUE THREAD

**Issue by tahseen2k8** [mk-j/PHP_XLSXWriter#104]
Hi
Thanks for a supper library . its time to get rid from phpExcle. :)
I had integrated your class in my code and its working super fast then 
old phpExcle class .
now what I need is to style up header just want to increase font size and 
all row color into black. i had tried but not succeed can you please share some 
sample code with me to do this .

$header['col1] = 'string';
        $header['col2'] = 'integer';
        $header['col3'] = 'string';
        //$styles1 = array( 'font'=>'Arial','font-size'=>10,'font-style'=>'bold', 'fill'=>'#eee', 'halign'=>'center', 'border'=>'left,right,top,bottom');
        $writer->writeSheetHeader('Invoice', $header);

so here is my code and i want to pass this $styles1 array as custom style can you please guide me
how can this possible . your quick response will be highly appreciated

**Comment by mk-j** [comment]
I'm not sure if this will work in your exact situation, but you may want to consider:
 $writer->writeSheetHeader('Invoice', $header, $suppress_first_row=true);
Then this call is styleable and becomes your new first row.
 $writer->writeSheetRow()

**Comment by RenanMuratori** [comment]
Any update on this issue?
I tried the solution with "$suppress_first_row=true", but excel reports errors on the generated xlsx file.

**Comment by masnecek** [comment]
Will be there a possibility to set own format for cells in header (different style than style of other sheet rows)?

**Comment by Mayrhofer94** [comment]
i fixed it with changing the writeSheetHeader function to:
```
public function writeSheetHeader($sheet_name, array $header_types, $suppress_row = false, $style=null)
    {
        if (empty($sheet_name) || empty($header_types) || !empty($this->sheets[$sheet_name]))
            return;

        self::initializeSheet($sheet_name);
        $sheet = &$this->sheets[$sheet_name];
        $sheet->columns = $this->initializeColumnTypes($header_types);
        if (!$suppress_row)
        {
            $header_row = array_keys($header_types);

            $sheet->file_writer->write('<row collapsed="false" customFormat="false" customHeight="false" hidden="false" ht="12.1" outlineLevel="0" r="' . (1) . '">');
            foreach ($header_row as $c => $v) {
                $cell_style_idx = empty($style) ? $sheet->columns[$c]['default_cell_style'] : $this->addCellStyle( 'GENERAL', json_encode(isset($style[0]) ? $style[$c] : $style) );
                $this->writeCell($sheet->file_writer, 0, $c, $v, $number_format_type='n_string', $cell_style_idx);
            }
            $sheet->file_writer->write('</row>');
            $sheet->row_count++;
        }
        $this->current_sheet = $sheet_name;
    }
```
found this answer somewhere around here

**Comment by mk-j** [comment]
This was solved in https://github.com/mk-j/PHP_XLSXWriter/pull/94 and is available in an upcoming branch/release https://github.com/mk-j/PHP_XLSXWriter/tree/2017-07-0.35-rc1

**Comment by samsong** [comment]
This is an important point by Mayrhofer94 that should be mention in the instruction usage.

If you want to specify a column style for header you MUST first set column 0 in the array of style because the code checks if $header_style[0] isset to decide whether to apply the column specific style or generic style.

I had this same problem!!
