### ISSUE TITLE
Total number of characters that a cell can contain

### ISSUE THREAD

**Issue by arku3** [mk-j/PHP_XLSXWriter#108]
I am not sure it's in xlsx specification or it's the limit of MS Excel only. The Total number of characters that a cell can contain is 32767 characters. Please consider throw an Exception or truncate the string if necessary.

<https://support.office.com/en-us/article/Excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3#ID0EBABAAA=Excel_2016-2013>

**Comment by mk-j** [comment]
Thanks for the idea... i'm not very excited about adding too many additional checks each time we write a cell, as it could slow down the overall time for producing a large 50K+ row spreadsheet.  But I'll think about it, maybe run some tests.... maybe there is a way to balance performance, code simplicity, and max cell size checks.
