### ISSUE TITLE
Enable line wrap and create using formula

### ISSUE THREAD

**Issue by Mayrhofer94** [mk-j/PHP_XLSXWriter#114]
Is it possible to enable line wrap within a column from source? i want to write a string like ="ABC"&CHAR(10)&"DEF" but i always the formular itself instead of the line wrap and i can't manage to enable line wrap.

**Comment by mk-j** [comment]
https://github.com/mk-j/PHP_XLSXWriter/blob/2017-07-0.35-rc1/xlsxwriter.class.php
The following wrap text code sample works in the above branch:
```
$writer = new XLSXWriter();
$writer->writeSheetHeader('Sheet1', ["col1"=>"string", "col2"=>"string"], $col_options = array('widths'=>[10,10]) );
$writer->writeSheetRow('Sheet1', array(101,'="ABC"&CHAR(10)&"DEF"'  ), $row_options = array('height'=>30,'wrap_text'=>true));
$writer->writeSheetRow('Sheet1', array(201,'this text is hidden'    ));
$writer->writeSheetRow('Sheet1', array(301,'this text will not wrap'));
$writer->writeToFile('xlsx-wrap.xlsx');
```

**Comment by Mayrhofer94** [comment]
@mk-j thanks for your help and reply.
Adding the "line wrap" flag this way works awesome for me. The only problem i got now is how to add the line break itself. When i try adding it with CHAR(10) or ZEICHEN(10) for German Excel the Cell gets formatted as text. If I format the cell from text to default and hit enter it seems working. I also tried using "\r\n" to force the line break.  My source looks like:

```
//writes header rows
const TYPE_GENERAL = 'general';
const TYPE_STRING = 'string';
//for type i tried string and general here..
$header_list[strip_tags($header_col_name)] = $type;
$style_header = array('font-style' => 'bold', 'suppress_row'=>false);
$objPHPXlsx->writeSheetHeader($xlsx_sheetname, $header_list, $style_header);

//replace tags
foreach($breaks AS $tag){
 if(strpos($item, $tag)) {
  $item = "=\"$item\"";
  $item = str_ireplace($breaks, "\"&ZEICHEN(10)&\"", $item);
  break;
 }
}
$row_values[$index] = $item;
//write row
$objPHPXlsx->writeSheetRow($xlsx_sheetname, $row_values, $row_options = array('wrap_text'=>true, 'height'=>30));
```

I would really appreciate if you could help me again :)

regards Dom

**Comment by mk-j** [comment]
Okay one thing at a time, I just made a commit on the 2017-07 branch, which should allow newline characters.  Let me know if it works.  Then we can look at your other issues (with the equals etc).

**Comment by Mayrhofer94** [comment]
Using the newline character ("\n") works like a charm now. I don't need to use a formula anymore which means the other problem got solved too. Thanks for your help you are my hero of the day!

**Comment by kanchan17** [comment]
Could you please share an example using "\n"
