### ISSUE TITLE
Styles Example Syntax Error

### ISSUE THREAD

**Issue by patrickporteous** [mk-j/PHP_XLSXWriter#115]
Hi, thanks for the work on this extension/plug-in, etc... I've been able to get all of the example files working except ex03-styles.php.  When I look at my log files I receive the following error when the page loads:

PHP Parse error:  syntax error, unexpected '[', expecting ')' in /var/www/html/cred/php-xlsx-writer/examples/ex03-styles.php. 

I'm trying to debug it by looking at your class but since the documentation is a little a sparse, I thought you might have a simple fix to address the styling without digging that deep in the code? 

Thank you

**Comment by mk-j** [comment]
What version of PHP are you running? 

The example is using a php 5.4 style array syntax with square brackets.  I think you would get this error if you were running php 5.3

**Comment by patrickporteous** [comment]
I an running php-5.3.8-1.el5.remi, is there a work around for 5.3?

**Comment by mk-j** [comment]
All I did was find-replace the php 5.4 array syntax with a php 5.3 compatible, and produced:
```
$styles1 = array( 'font'=>'Arial','font-size'=>10,'font-style'=>'bold', 'fill'=>'#eee', 'halign'=>'center', 'border'=>'left,right,top,bottom');
$styles2 = array( array('font-size'=>6),array('font-size'=>8),array('font-size'=>10),array('font-size'=>16) );
$styles3 = array( array('font'=>'Arial'),array('font'=>'Courier New'),array('font'=>'Times New Roman'),array('font'=>'Comic Sans MS'));
$styles4 = array( array('font-style'=>'bold'),array('font-style'=>'italic'),array('font-style'=>'underline'),array('font-style'=>'strikethrough'));
$styles5 = array( array('color'=>'#f00'),array('color'=>'#0f0'),array('color'=>'#00f'),array('color'=>'#666'));
$styles6 = array( array('fill'=>'#ffc'),array('fill'=>'#fcf'),array('fill'=>'#ccf'),array('fill'=>'#cff'));
$styles7 = array( 'border'=>'left,right,top,bottom');
$styles8 = array( array('halign'=>'left'),array('halign'=>'right'),array('halign'=>'center'),array('halign'=>'none'));
$styles9 = array( array(),array('border'=>'left,top,bottom'),array('border'=>'top,bottom'),array('border'=>'top,bottom,right'));
```
Its clearly more readable the other way, however.

**Comment by patrickporteous** [comment]
Cool, that worked perfectly.  I appreciate the help.

I left another comment on the following issue:
Error-"Excel finds unreadable content in file... do you want to recover contents of this workbook"? #103
It's marked as Closed.  Should I open a new thread or will you see the question there and replay if you have a solution?

**Comment by Buccleuch** [comment]
It doesn't make sense that we must remove German characters to be able to export to Excel. @patrickporteous what character encoding existed when you encountered problems exporting with ü in the string? Is there any other reason this could happen?
