### ISSUE TITLE
When to expect next release

### ISSUE THREAD

**Issue by david-ridgeonnet** [mk-j/PHP_XLSXWriter#116]
Hello,

I've started using your library and realised that two of the critical things I need are in the "unreleased version" (2017-07). These are `wrap_text` and the new line characters not being stripped...

I was wondering when you expect this will be released?

Thanks
David

**Comment by mk-j** [comment]
Initially I was planning on doing the release July 2017.  That 2017-07 branch is stable.  The only thing left on it, is to add another feature (hyperlinks).  But if I get time in june to add that feature, it might go out in mid-june.

**Comment by david-ridgeonnet** [comment]
Okay thanks, and thank you for taking time to reply. Unfortunately I found another package that does it and as the XLSX files are only a few rows for me performance isn't a great concern at the moment. I'll keep this repo bookmarked for future reference though.
