### ISSUE TITLE
PHP_XLSXWriter-2017-07-0.35-rc1 - Suppress Header Depreciated

### ISSUE THREAD

**Issue by patrickporteous** [mk-j/PHP_XLSXWriter#117]
Hi,
I hope you don't mind me asking a question about the Release Candidate package but with this change you have updated the class to accept column widths (awesome) but line 190 in the xlsxwriter.class.php notes the following:

self::log( "Warning! passing $suppress_row=false|true to writeSheetHeader() is deprecated, this will be removed in a future version." );

I need to be able suppress the header in my Excel file and have tried adding:

$col_options = array('widths'=>array(11,11),'suppress_row'=>array(1) );
(* Note I'm running php-5.3.8-1 so I had to modify the width syntax to work with my version)
When my page loads I'm getting the following error:
PHP Fatal error:  Call to undefined function boolval()
Is this function still under development or am I passing the array value incorrectly?

Thanks!

**Comment by mk-j** [comment]
try:
```
$col_options = array('widths'=>array(11,11),'suppress_row'=>true );
```

**Comment by mk-j** [comment]
Moving question from pull requests: 
"Would you consider adding the ability to freeze panes and add filter drop downs in an upcoming release? Thanks for all the work on this project. - patrickporteous"

Sure, i'm not sure how to freeze panes, and add filter drop downs, but I might look into it one day.

**Comment by patrickporteous** [comment]
Thank you,

I tried adding the $col_options you suggested and I'm still getting an error.  Here is the error I receive:

 Call to undefined function boolval() in /var/www/html/php-xlsx-writer-rc1-test/xlsxwriter.class.php on line 187

I was able to temporarily get around the error  by commenting out the row and adding the following:

//$suppress_row = isset($col_options['suppress_row']) ? boolval($col_options['suppress_row']) : false;
$suppress_row = true;	

I know this is a temporary fix but worked.  I think the problem is that the function boolval() you're calling doesn't exist in the xmlwriter.class.php file.  If it does, I couldn't find it in the files I downloaded.  I somewhat see the logic you're following but didn't want to muck around in there too much if you're planning to add other features based on what you have started.

Thank you for considering the freeze panes and filter drop downs in your upcoming release.

**Comment by mk-j** [comment]
Yeah i guess boolval is php 5.5+, i'll go fix that when i get a sec.  I can see that would cause a compatibility issue if you're on php 5.3

**Comment by patrickporteous** [comment]
Cool, thank you for taking the time to take a look at this issue.  If you can point me in the right direction, I'd be happy to assist with the correction.

**Comment by mk-j** [comment]
I'll let you know when I have something for you to test.

**Comment by mk-j** [comment]
Okay I removed boolval, you can go try https://github.com/mk-j/PHP_XLSXWriter/tree/2017-07-0.35-rc1  again to check for php 5.3

**Comment by AzzaAzza69** [comment]
Please see https://github.com/mk-j/PHP_XLSXWriter/issues/137 for code to freeze the panes...
