### ISSUE TITLE
How to custom cell for temperature values  based on value ?

### ISSUE THREAD

**Issue by AymanElarian** [mk-j/PHP_XLSXWriter#121]
hello , thanks for your class , its really fast , simple , good 

 i have to do some thing like this 
<img width="704" alt="screen shot 2017-06-01 at 1 26 31 am" src="https://cloud.githubusercontent.com/assets/364872/26656849/7b251f5c-4669-11e7-9500-85e8b48556ae.png">

it must color cell based on value , how to achive , that 

, thats what i have done right now 
<img width="1051" alt="screen shot 2017-06-01 at 1 24 50 am" src="https://cloud.githubusercontent.com/assets/364872/26656882/901c15aa-4669-11e7-91a7-04d37c6b4239.png">

**Comment by mk-j** [comment]
The only way to implement this, is to use php to decide the background color based on the value at the time your write it out to excel.  Hardcoding the style like that is not ideal, but the closest you can come to achieving what you are looking to do here.... as it does not currently support using the excel feature which allows the style of a cell to change based on its value.

**Comment by AymanElarian** [comment]
@mk-j  okey i can do that , how can i color selected cells in row ?

**Comment by AymanElarian** [comment]
@mk-j  any help please ?  any document on how to color exact cell

**Comment by mk-j** [comment]
ex03-styles.php has an example of this.
