### ISSUE TITLE
Excel 2013 cannot open the generated file

### ISSUE THREAD

**Issue by emperorflame** [mk-j/PHP_XLSXWriter#122]
I cannot open the generated file, this is a real headache for me 'cause in another website it works. Please could you help me with this?

**The error message i've got:**
"Excel found unreadable content in 'example.xlsx' . Do you want to recover the contents of this workbook? If you trust the source of this workbook, click Yes. "

**Code:**

        $returnArray = [
            ['name','email','company','message','profession','download_type','download_date','ip_address']
        ];

        $header = array(
            'Name'=>'string',
            'Email'=>'string',
            'Company'=>'string',
            'Message'=>'string',
            'Profession'=>'string',
            'Download Type'=>'string',
            'Download date'=>'string',
            'IP address'=>'string',
        );

        $name = 'example.xlsx';
        $writer = new XLSXWriter();
        $writer->setAuthor('Ledblade');
        $writer->writeSheet($returnArray,'Example',$header);
        $writer->writeToFile($name);

[example.xlsx](https://github.com/mk-j/PHP_XLSXWriter/files/1074604/example.xlsx)

**Comment by mk-j** [comment]
Have you tried the other branch: https://github.com/mk-j/PHP_XLSXWriter/tree/2017-07-0.35-rc1

**Comment by premax** [comment]
In my case it happened because I've set the value of a cell to more than 32767 characters and that is a maximum for Excel 2007 format.

**Comment by timothy812c** [comment]
In my case, this error appears depending on the amount of record that I generate. When I generate few records(100 below) the error appears, but it does not appear when I generate many records(500 above).
