### ISSUE TITLE
Allow to update column format

### ISSUE THREAD

**Issue by Shnoulle** [mk-j/PHP_XLSXWriter#124]
I have a project where i need different (cell) format on each line.

Some can be : string;integer;percentage;percentage;percentage;
Some other : string;integer;number(2 decimal);

For example, see the attached file
[XLSXWriter.xlsx](https://github.com/mk-j/PHP_XLSXWriter/files/1083439/XLSXWriter.xlsx)

I think it can be great to allowing update cell format for other.

I make a quick test (and make the pull request tomorrow)

```
	public function updateFormat($sheet_name, array $header_types) {
		if (empty($sheet_name) || empty($header_types))
			return;
		if(empty($this->sheets[$sheet_name])) {
			$this->writeSheetHeader($sheet_name, $header_types, false);
			return;
		}
		$sheet = &$this->sheets[$sheet_name];
		$sheet->columns = $this->initializeColumnTypes($header_types);
		$this->current_sheet = $sheet_name;
	}
```
Seems OK .

I think new function can be setFormat. Only used to set format (no header)

Else thanks; good job 👍

**Comment by Shnoulle** [comment]
Please : see the pull request

**Comment by mk-j** [comment]
`$writer->writeSheetHeader('Sheet1', $header1);
$writer->writeSheetRow('Sheet1', $row1 );
$writer->writeSheetHeader('Sheet1', $header2);
$writer->writeSheetRow('Sheet1', $row2);
`
you should be able to do this now.
