### ISSUE TITLE
Automatic height

### ISSUE THREAD

**Issue by Shnoulle** [mk-j/PHP_XLSXWriter#127]
Using https://github.com/mk-j/PHP_XLSXWriter/tree/2017-07-0.35-rc1 if i set width of column and no height for a cell with 'wrap_text'=>true : the height of the cell seems fixed and then i see only the last line.

After, opening in LibreOffice (i don't have excel) : just update the cell format fix the height.

I didn't know if there are a auto keyword for ht :(

**Comment by mk-j** [comment]
I think you'll have to manually set the cell height.

**Comment by Shnoulle** [comment]
I don't know with Excel, but with LibreOffice : set the height to 'auto', adding text in the cell update the height.

I look at the xml to have the keyword, maybe it can be done ;)

**Comment by mk-j** [comment]
The xml for a row looks like this, (height 12.1)
```
    <row collapsed="false" customFormat="false" customHeight="false" hidden="false" ht="12.1" outlineLevel="0" r="1">
      <c r="A1" s="0" t="n">
        <v>2003</v>
      </c>
```
I don't think there is a way to put 'auto' in there.
