### ISSUE TITLE
Column format overriding text in date column

### ISSUE THREAD

**Issue by eclectus** [mk-j/PHP_XLSXWriter#128]
First - Thank you so much, this class is a true life saver for projects with thousands of data rows to export to excel.

When setting the format in writeSheetHeader as 'date' (or one of the date strings - in my case "DD/MM/YYYY"), if a TEXT value is entered in that column, it displays in the sheet as 00/01/1900.
This causes a problem for mixed data, and also if the column headings are not on first row i.e. when you want to enter some title rows before the data table, then those column names cannot be displayed correctly.

I have made a workaround to allow row-level format to override the column format for any or all the cells in that row. 
Basically I add a parameter (array) that is passed with the formats for each cell in the row, or just one value to apply to all cells in this row (i.e. 'string' in a column header's row).
Then when creating the cell value, I change the number format fields to have the passed value, otherwise reverts to column format which your code does.
Please review and consider adding to the PHP_XLSXWriter-2017-07-0.35-rc1 which seems to deal with other formatting issues.
```php
public function writeSheetRow($sheet_name, array $row, $row_options=null, $row_formats=null)
	.
	.
	.
	$style = &$row_options;
	$format = &$row_formats;
	$c=0;
	foreach ($row as $v) {
		if (empty($format)) {
			$number_format = $sheet->columns[$c]['number_format'];
			$number_format_type = $sheet->columns[$c]['number_format_type'];
		}
		else {
			$number_format = self::numberFormatStandardized(isset($format[$c]) ? $format[$c] : $format[0]);
			$number_format_type = self::determineNumberFormatType($number_format);
		}
		$cell_style_idx = empty($style) ? $sheet->columns[$c]['default_cell_style'] : $this->addCellStyle( $number_format, json_encode(isset($style[0]) ? $style[$c] : $style) );
		$this->writeCell($sheet->file_writer, $sheet->row_count, $c, $v, $number_format_type, $cell_style_idx);
```

**Comment by mk-j** [comment]
You said the date comes out as "00/01/1900", what string are you passing in to php xlsx writer?

**Comment by eclectus** [comment]
Just a test string. In my case the columns were 'Transaction Date', 'Charge Date', 'Creation Date', and 'Update Date'

**Comment by mk-j** [comment]
What date did you pass in ?

**Comment by eclectus** [comment]
I wrote - I did not pass a date, I passed the Name of the Column, the TEXT which I wrote in the last message. Why don't you just recreate it - I gave you all the input.

**Comment by Shnoulle** [comment]
I have same issue with 0% in fact. I can make a example if needed but if set array('string','0%') and add a line with array('string','string') : the second string show 0% (on LibreOO). 

It's the reason of this merge request : https://github.com/mk-j/PHP_XLSXWriter/pull/126

**Comment by eclectus** [comment]
Your updateFormat is great, and very important when you change the table format like your example.

My request is to be able to insert a different format for an individual line in the same table.
This is always needed for column header if they are not in the first row.
Also if you want to insert in the middle of a table a row with other formats  i.e. every end-of-month in the DATE column you want to enter just MM/YYYY or the text 'Total for Month', and then the SUM of values for that month - and after that row continue the regular format for the next month etc.

I would love to see both your commit and the above revision in the next release.

**Comment by Shnoulle** [comment]
i use it in a project, updating header format at each line ;) , It work :)

**Comment by seba627** [comment]
It works, but if forces you to use cell style, you can avoid cell style changing:
`$cell_style_idx = empty($style)`

by 

`$cell_style_idx = empty($style) && empty($format)`

Thanks!
