### ISSUE TITLE
date formatted column fails on linux

### ISSUE THREAD

**Issue by eclectus** [mk-j/PHP_XLSXWriter#129]
When running the code on a Windows (XAMPP) server, the 'date' formatted column appears correctly  in the excel sheet [Excel 2010]. 
However, running the same code with the same database in a Linux server, creates excel with '1900-01-00' for all rows in the 'date' column. 
The data is a DATE field in the MySQL database.
```php
$colFormats = array('integer','string','date');

$writer = new XLSXWriter();

foreach ($sources as $source) {
	// start new source sheet
	$writer->writeSheetHeader($source['name'],$colFormats,true); // sheet name, formats

	$trans = loadTransactions($conn);
	foreach ($trans as $tran) {
		$writer->writeSheetRow($source['name'], $tran);
	}
}
$downloadFileName = 'TransactionsReport_' . date('d-m-Y') . '.xlsx';
$filePath = './reports/';
$writer->writeToFile($filePath . $downloadFileName);

	
function &loadTransactions($db){
	$stmt = "SELECT id, transaction, tran_date FROM transactions";

	$select = $db->prepare($stmt);
	$select->execute();
	$result = $select->fetchAll(PDO::FETCH_ASSOC);
	
	return $result;
}
```

**Comment by mk-j** [comment]
What date was displayed as '1900-01-00'?

**Comment by eclectus** [comment]
All of them

**Comment by mk-j** [comment]
I'm asking for sample data... to see what kind of date gets formatted as '1900-01-00'.

Try replacing:
```$writer->writeSheetRow($source['name'], $tran);```
with 
```print_r($tran); die(); $writer->writeSheetRow($source['name'], $tran);```
So we can see the actual data thats going into the spreadsheet.  For instance, if the date coming from your mysql database is 0000-00-00 or 9999-12-31, that may not be a valid value in an xlsx file.

**Comment by eclectus** [comment]
Maybe you didn't understand my initial report about the bug.
Here are the facts:
- the database contains ALL valid dates for all records
- we are talking about 5 sheets of ~3,000 rows each
- when running the program WITHOUT formatting the column as date, all rows show the valid dates (however as an Excel text cell)
- when running on a Windows server AND formatting column as date, all rows show the valid date (this time as an Excel date cell)
- when running on Linux server AND formatting column as date, all rows show the 1900-01-00 value where the valid date was returned from the database

I hope now its clear.
There is no problem with the data, or with receiving the data from the database, the problem is the interpretation of the formatted column of the data when its run under linux.

Example: '2013-05-22'
General format: '22/05/2013' as text (cannot be filtered as date)
Date format under Windows: '22/05/2013' as date
Date format under Linux: '00/01/1900'

**Comment by mk-j** [comment]
```php
<?php
include_once("xlsxwriter.class.php");
$colFormats = array('column1'=>'integer','column2'=>'string','column3'=>'date');
$tran = array('5','str','2013-05-22');
$writer = new XLSXWriter();
$writer->writeSheetHeader('Sheet1',$colFormats); // sheet name, formats
$writer->writeSheetRow('Sheet1', $tran);
$downloadFileName = 'TransactionsReport_' . date('d-m-Y') . '.xlsx';
$writer->writeToFile($downloadFileName);
```
So you are saying this example produces:
 ```'5','str','00/01/1900'``` under linux, and ```'5','str','22/05/2013'``` under windows?

I'm unable to reproduce your issue.  When I run this in linux it always shows ```'5','str','2013-05-22'``` in the resultant spreadsheet.

**Comment by JulieC35** [comment]
Hello,

I think it is too late to help you but if someone read this topic again...
I has the same problem because my number of columns don't correspond with the number of data for each row. I forgot a column name in my header array, that's fix the problem.
