### ISSUE TITLE
How to add two header rows 

### ISSUE THREAD

**Issue by rajeshdk** [mk-j/PHP_XLSXWriter#130]
Hi,
I want to add two header rows in a document. 
![image](https://user-images.githubusercontent.com/11823896/27875877-716f09d0-61d2-11e7-8ae7-86b07f4da2f8.png)
It is possible?

Thanks

**Comment by mk-j** [comment]
i think you can call writeSheetRow() one time before writeSheetHeader() and it would probably work.

**Comment by rajeshdk** [comment]
Solved

**Comment by markruys** [comment]
Well, for me it doesn't work.

Code:
~~~
$writer = new XLSXWriter();
$writer->writeSheetRow('Sheet1', array("aaaaaaaa"));
$writer->writeSheetHeader('Sheet1', array("XXXXXXXX"=>'string'));
$writer->writeSheetRow('Sheet1', array("bbbbbbbb"));
~~~

Then I get: 
<img width="150" alt="schermafbeelding 2017-10-28 om 22 21 24" src="https://user-images.githubusercontent.com/602953/32138153-8a047ce4-bc2e-11e7-88b2-1f55eadd7260.png">

As you can see the header row disappears. How did your solution look like @rajeshdk ?

Office 2017 Mac, generated Excel:
[header.xlsx](https://github.com/mk-j/PHP_XLSXWriter/files/1424593/header.xlsx)

**Comment by denuu** [comment]
I get the same result as above @markruys - the header row simply vanishes.
