### ISSUE TITLE
add row style error on php 5.3

### ISSUE THREAD

**Issue by to672000** [mk-j/PHP_XLSXWriter#133]
Hi mk-j,

My website run on linux server and php 5.3.13 version, I try the PHP_XLSXWriter-2017-07-0.35-rc1 to add the wrap_text style to the row, but php after run the writeToFile function, will export the error xlsx file.

I found that if not add any style to the row, the export xlsx function is not any problem.

This is the bug on php 5.3? or add style not support php 5.3?

Eric

**Comment by mk-j** [comment]
What is the error its giving?  Can you look at the corrupted xlsx file in a hex editor?

**Comment by jack33232** [comment]
@to672000  The reason is that the function "bootval" is not available in PHP 5.3. You can just write one with a function_exists checking.

**Comment by mk-j** [comment]
this will be fixed in the next version (to support php 5.3 again)
