### ISSUE TITLE
How to Stream an export

### ISSUE THREAD

**Issue by RobRademeyer** [mk-j/PHP_XLSXWriter#134]
If I take **example.php** from your root directory and modify the last few lines as follows:

    $writer->writeToFile($filename);
    readfile($filename);
    exit();

it correctly generates the Excel spreadsheet and the browser opens a File, Save As dialog from which I can save the spreadsheet and open it successfully in Excel.

When I apply the same technique to a slightly more complex example, I am unable to open the Excel spreadsheet which is saved from the File, Save As dialog. However, I *am* able to successfully open the original file generate by the `writeToFile()` method.

The error I get is `Excel cannot open the file nnnnn.xlsx because the file format or file extension is not valid`. But remember, I *can* open the original file, and doing a file compare indicates that the two files are identical!

**What is the correct method for achieving this i.e. for generating the Excel spreadsheet and immediately streaming it to the browser so that the user can save it locally?**

**Comment by mk-j** [comment]
You'll have to look more closely into your server logs to see what is going on.  The headers in example.php have worked fine for me.  If you get "Excel cannot open the file" its possible a php warning in your "more complex example" is corrupting the file somehow.

**Comment by saigadekar** [comment]
You can use this code to download the file locally once it is generated.
  
  $writer->writeToFile($fileLocation);
 
  header('Content-Description: File Transfer');
  header("Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
  header("Content-Disposition: attachment; filename=\"".basename($fileLocation)."\"");
  header("Content-Transfer-Encoding: binary");
  header("Expires: 0");
  header("Pragma: public");
  header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
  header('Content-Length: ' . filesize($fileLocation)); //Remove

  ob_clean();
  flush();

  readfile($fileLocation);
  unlink($fileLocation);
 exit(0);

**Comment by chicosilva** [comment]
I change this line:


header("Content-Disposition: attachment; filename=".basename($fileLocation));
