### ISSUE TITLE
PHP 5.4.16 render a non-readable file

### ISSUE THREAD

**Issue by med-ezzairi** [mk-j/PHP_XLSXWriter#139]
Hi all,
Following the very first basic example, 
- PHP 7.* it produce a readable file (*.xlsx) but on PHP 5.4.16 (production env) it produce a non-readable file format (Excel shows an error "File Format or Extension is not valide")

NB: same code portion is used under both (PHP 5.4 and PHP 7)
can help or just fix that??

**Comment by mk-j** [comment]
Look at the "corrupted" file in a hex editor, perhaps your server is configured with display_errors=True, and you're emitting a php warning, which is corrupting the xlsx file.

Another way to check this is using command line php.

**Comment by med-ezzairi** [comment]
Thank you Sir for your replay, but the basic example I'm using contains no error/warning.

and for the CLI (I'm not able to do that cause I have no SSH access to the servers)

here's the code

require './xlsxwriter.class.php';

$header = array(
	'font-size'=>14,'font-style'=>'bold',
	'fill'=>'#eee', 'halign'=>'center', 'valign'=>'center',
	'border'=>'left,right,top,bottom',
	);

$cells = array(
	array('font-size'=>12,'halign'=>'left','valign'=>'center'),
	array('font-size'=>12,'halign'=>'left','valign'=>'center'),
	array('font-size'=>12,'halign'=>'right','valign'=>'center'),
	);

$data = array(
    array('User Name','City','Amount'),
    array('Jacob Lavo','Rabat','220'),
    array(''),
    array('Conita Balos','Esta Monto','153.5'),
);

$filename = "example.xlsx";
$sheetName="June 2017";

$writer = new XLSXWriter();
$writer->writeSheetRow($sheetName,$data[0],$header);
$writer->writeSheetRow($sheetName,$data[1],$cells);
$writer->writeSheetRow($sheetName,$data[2],$cells);
$writer->writeSheetRow($sheetName,$data[3],$cells);
$writer->writeToFile($filename);

header("Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
header('Content-disposition: attachment; filesize="'.filesize($filename).'"');
header('Content-disposition: attachment; filename='.$filename);
echo file_get_contents($filename);
exit;

**Comment by premax** [comment]
Please attach the XLSX file (output from the above code).

**Comment by VladGogolev** [comment]
@med-ezzairi 
Try to add ob_clean() and ob_end_flush() before headers. 
That would work.
