### ISSUE TITLE
The second worksheet is still abnormal.

### ISSUE THREAD

**Issue by microkof** [mk-j/PHP_XLSXWriter#14]
$data2 = array(
    array('2003','01','343.12'),
    array('2003','02','345.12'),
);

After my test, all content of the second worksheet is
![image](https://cloud.githubusercontent.com/assets/5286586/4673188/9a547f08-559e-11e4-9b4b-7efbae9ced1a.png)
So this means that "array('2003','01','343.12')" is lost.

**Comment by mk-j** [comment]
This should be fixed properly in the latest version 0.30
