### ISSUE TITLE
Excel cannot open the file created by XLSXWriter when use $_SESSION

### ISSUE THREAD

**Issue by eclipseee13** [mk-j/PHP_XLSXWriter#142]
Hi!
I use PHP_XLSXWriter in my "downloadFile.php" to create and download my file; the content of the sheet came out from a query. (Example: select * from table where user="aaa";)

When I run the script directly from the browser setting in the file $user="aaa", everything works perfectly and the downloaded file is perfect but I need to run the script by another page so I put in my interface

`<a id="downloadXlsx" name="downloadXlsx" type="button" href="downloadFile.php" class="btn btn-default ">Download Excel</a>`

and in "downloadFile.php" I retrieve $user from $_SESSION['user'] variable.

However in this case the downloaded file is corrupted because Excel cannot open it and reports the message 
"Excel cannot open the file 'xxx' because the file format or file extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file."

Someone can help me? Thank you

**Comment by VladGogolev** [comment]
If your script works correctly via direct run, it means your script is ok and theres no problem with XLSXWriter.
First of all, try to check that **session** starts correctly. Very common problem is the error in **session.save_path**.

Also, try to check **errors**.
```
ini_set('display_startup_errors',1);
ini_set('display_errors',1);
error_reporting(-1);
```

**Comment by virusczz** [comment]
for me was easy in the Wamp to make this work: add to the script: 
ob_clean();
flush();

**Comment by erfan-azhdari** [comment]
thanks, @virusczz your solution worked perfectly.
