### ISSUE TITLE
String starting with `=` incorrectly interpreted as a formula

### ISSUE THREAD

**Issue by lxa** [mk-j/PHP_XLSXWriter#147]
Here https://github.com/mk-j/PHP_XLSXWriter/blob/master/xlsxwriter.class.php#L328 it assumes that any string starting with `=` is a formula, which is obviously not so - resulting in bad formulas in generated XLSX. (Excel pops up the error `Excel found unreadable content in '[filename].xlsx'. Do you want to recover the contents of this workbook? If you trust the source of this workbook, click Yes.`)

Possible workaround: https://github.com/lxa/PHP_XLSXWriter/commit/b2613480712969218c2c5db317439012fed514e3

**Comment by mk-j** [comment]
Its not a bug, its a feature.... any cell starting with = tells PHP_XLSXWriter the cell contains a formula.
Look at examples/ex01-multiple-sheets.php:
It has =B2 okay thats a formula
And '=B2 okay thats not a formula, thats the string "=B2"

**Comment by lxa** [comment]
Got it; so I escape `=` with `'`. but how do I escape the `'`?

**Comment by mk-j** [comment]
The ' thing is not specific to PHP_XLSXWriter, its for excel/libreoffice etc. Prepending anything with ' turns it into a text field... so you could prepend 'aint with a single ' as in ''aint to force it to be a text field, and 55 to '55 etc.

**Comment by lxa** [comment]
Now its clear, thanks!
