### ISSUE TITLE
New lines only appear after Save & Open

### ISSUE THREAD

**Issue by markruys** [mk-j/PHP_XLSXWriter#153]
I'm trying to get new lines inside a header cell. Only after I open the document, save it, and reopen it, the contents are as expected.

Code:
~~~
$writer = new XLSXWriter();
$writer->writeSheetHeader('Sheet1', array("1\n22222222"=>'string'),
    $col_options = array('height'=>30,'wrap_text'=>true));
$writer->writeSheetRow('Sheet1', array("a\nbbbbbbbb"),
    $row_options = array('height'=>30,'wrap_text'=>true) );
~~~

Opened before a save:
<img width="109" alt="before save" src="https://user-images.githubusercontent.com/602953/32138082-48b05ad4-bc2d-11e7-8f1c-53eb75715c1c.png">

And after a save & reopen:
<img width="122" alt="after save" src="https://user-images.githubusercontent.com/602953/32138086-566964ae-bc2d-11e7-9a1a-6f242929d75c.png">

These are the Excels:
* [Before save.xlsx](https://github.com/mk-j/PHP_XLSXWriter/files/1424579/Before.save.xlsx)
* [After Save.xlsx](https://github.com/mk-j/PHP_XLSXWriter/files/1424581/After.Save.xlsx)

Excel Mac Office 2017

**Comment by mk-j** [comment]
Don't mac's use \r as their newline character?  Have you tried using \r\n CRLF instead of \n so its more compatible?

**Comment by markruys** [comment]
I've unpacked the xlsx file, ran unix2dos on the contents, and zipped it back. Same result, so \n or \r\n does not make a difference.

**Comment by huang-winter-snow** [comment]
The text "abc\r\ndef", on the mac, I have the same problem, the same file can be wrapped under the window
