### ISSUE TITLE
Corrupted file output, writeToStdOut

### ISSUE THREAD

**Issue by Synida** [mk-j/PHP_XLSXWriter#154]
Hi guys!

I have an issue with the writeToStdOut function, and i dont really know what's going on. When I try to write my array to a file, then everything is working fine. But it the case if i'm trying to use the writeToStdOut function i got a corrupted file as a result:
![2017-10-31_102906](https://user-images.githubusercontent.com/14039463/32216840-67e26546-be26-11e7-9880-6183cbd0bfe9.png)

My code is simple; I replaced the individual population to a fromArray method, to speed up the excel file generation for the PHPExcel. Then I just replaced the writer as it was in the sample here, and the normal file writing worked perfectly, but somehow the writeToStdOut not. There is no error in the log.
`
        $writer = new XLSXWriter();
        $writer->writeSheet($excel);
        $writer->writeToStdOut();
`

When i try to use:
`
        $writer->writeToFile('php://output');`
then i got this error in the log:

> {"name":"PHP Warning","message":"ZipArchive::addEmptyDir(): Invalid or uninitialized Zip object","code":2,"type":"yii\\base\\ErrorException","file":"C:\\xampp\\htdocs\\portal\\api\\vendor\\mk-j\\php_xlsxwriter\\xlsxwriter.class.php","line":89,"stack-trace":["#0 [internal function]: yii\\base\\ErrorHandler->handleError(2, 'ZipArchive::add...', 'C:\\\\xampp\\\\htdocs...', 89, Array)","#1 C:\\xampp\\htdocs\\portal\\api\\vendor\\mk-j\\php_xlsxwriter\\xlsxwriter.class.php(89): ZipArchive->addEmptyDir('docProps/')","#2 C:\\xampp\\htdocs\\portal\\api\\common\\components\\export\\report\\ReportService.php(366): XLSXWriter->writeToFile('php://output')","#3 C:\\xampp\\htdocs\\portal\\api\\backend\\versions\\v1\\controllers\\ReportController.php(162): common\\components\\export\\report\\ReportService->exportReportFromArray(Object(common\\components\\export\\report\\ClientReport))","#4 [internal function]: backend\\versions\\v1\\controllers\\ReportController->actionClient()","#5 C:\\xampp\\htdocs\\portal\\api\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(57): call_user_func_array(Array, Array)","#6 C:\\xampp\\htdocs\\portal\\api\\vendor\\yiisoft\\yii2\\base\\Controller.php(156): yii\\base\\InlineAction->runWithParams(Array)","#7 C:\\xampp\\htdocs\\portal\\api\\vendor\\yiisoft\\yii2\\base\\Module.php(523): yii\\base\\Controller->runAction('client', Array)","#8 C:\\xampp\\htdocs\\portal\\api\\vendor\\yiisoft\\yii2\\web\\Application.php(102): yii\\base\\Module->runAction('v1/report/clien...', Array)","#9 C:\\xampp\\htdocs\\portal\\api\\vendor\\yiisoft\\yii2\\base\\Application.php(380): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))","#10 C:\\xampp\\htdocs\\portal\\api\\backend\\web\\index-test.php(21): yii\\base\\Application->run()","#11 {main}"]}

Is there anyone who has an idea?

**Comment by Synida** [comment]
headers:
`header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            header('Access-Control-Allow-Methods: GET');
            header('Access-Control-Allow-Origin: *');`

**Comment by mk-j** [comment]
"I replaced the individual population to a fromArray method, to speed up the excel file generation for the PHPExcel. "
This sounds like the issue.

If you want to speed it up... don't use `$writer->writeSheet($data);` but  write 1 row at atime.
```
$writer = new XLSXWriter();
foreach($rows as $row)
	$writer->writeSheetRow('Sheet1', $row);
```

I'm not really sure whats in "$excel" in your example, but thats likely the problem.

You'll have to provide a fully self-contained example of the php code which reproduces the failure.  You will need a few rows of static data, something like var_export(array_slice($mydata,0,3)) would produce that.  Something like:
```
$data = array(
    array('year','month','amount'),
    array('2003','1','220'),
    array('2003','2','153.5'),
);

$writer = new XLSXWriter();
$writer->writeSheet($data);
 $writer->writeToFile('php://output');
```

**Comment by Synida** [comment]
Thank you for your reply! And thanks for the tip!
In my code, the $excel value is an array, which is contains the headers and the rows too. Here is an example for the $excel value:
```
[
    0 => [
        'client_name' => 'CLIENT NAME'
        'industry_type' => 'INDUSTRY TYPE'
        'project_title' => 'PROJECT TITLE'
        'po_number' => 'PO NUMBER'
        'project_start_date' => 'PROJECT START DATE'
        'upload_date' => 'UPLOAD DATE'
        'file_due_date' => 'FILE DUE DATE'
        'client_type' => 'CLIENT TYPE'
        'email' => 'EMAIL'
        'audio_id' => 'AUDIO ID'
        'file_name' => 'FILE NAME'
        'type_of_transcript' => 'TYPE OF TRANSCRIPT'
        'turnaround' => 'TURNAROUND'
        'no_of_speakers' => 'NO. OF SPEAKERS'
        'document_format' => 'DOCUMENT FORMAT'
        'timestamps_time' => 'TIMESTAMPS TIME'
        'duration' => 'FILE DURATION (exact mins:seconds)'
        'billed_duration' => 'BILLED DURATION (minutes includes rounding)'
        'billing_rate' => 'BILLING RATE (£ per hour)'
        'billing_rate_minute' => 'BILLING RATE (£ per minute)'
        'price' => 'FILE COST (ex.vat)'
        'project_discount' => 'PROJECT DISCOUNT'
        'poor_audio' => 'POOR AUDIO'
        'discount' => 'DISCOUNT'
        'price_discount' => 'FILE COST (inc.vat and discounts)'
        'project_total' => 'PROJECT TOTAL (inc.vat and discounts)'
        'proofreader_name' => 'PROOFREADER NAME'
        'proofreader_rate' => 'PROOFREADER RATE'
        'payment_provider' => 'PAYMENT PROVIDER'
        'transaction_id' => 'TRANSACTION ID'
        'token_id' => 'TOKEN ID'
        'card_holder_name' => 'CARD HOLDER NAME'
        0 => 'TYPIST 1 NAME'
        1 => 'TYPIST 1 RATE'
        2 => 'TYPIST 2 NAME'
        3 => 'TYPIST 2 RATE'
        4 => 'TYPIST 3 NAME'
        5 => 'TYPIST 3 RATE'
    ]
    1 => [
        0 => 'Borat Sagdiyev'
        1 => ''
        2 => 'Invitation test #1'
        3 => '78TM2'
        4 => '16.08.2015'
        5 => '17.08.2015'
        6 => '17.08.2015'
        7 => 'business_account'
        8 => 'clientuser@gmail.com'
        9 => 2
        10 => 'Radio cut #1'
        11 => 'Summary'
        12 => '24 hour'
        13 => '4+ Speakers'
        14 => 'Word'
        15 => 'Every Speaker'
        16 => '5.20'
        17 => 320
        18 => '0'
        19 => '0'
        20 => '0'
        21 => '0'
        22 => '0'
        23 => '0'
        24 => '0'
        25 => '0'
        26 => ''
        27 => '0'
        28 => ''
        29 => ''
        30 => ''
        31 => ''
    ]
]
```
Actually when I try to save the array with the writeToFile function, then it's working fine, but i really want to write to the php://output

And the code what am I using for wrinting onto a file is this(updated with the suggested method):
```
        $writer = new XLSXWriter();
        $title = $this->workSheet->getTitle();
        foreach ($excel as $row) {
            $writer->writeSheetRow($title,$row);
        }
        $writer->writeToStdOut();
```

Thanks for your help!

**Comment by Synida** [comment]
Basically the writeToStdOut() writes something too, but it's only that garbage, what I'm posted in that picture. And if I make some mistakes myself, then it's writes the errors into the xlsx file too, but in this case, what I see is only there "docProps/", "docProps/app.xml", "docProps/core.xml", "PK" - the first characters in the file, but somewhere i read, that this must be this, "/worksheets/sheet1.xml" - so these are the readable words. And I found these only in the "xlsxwriter.class.php" and in the PHPExcel's classes

**Comment by Synida** [comment]
ugh, i just find out the problem. The front-end generated an xls file instead of an xlsx, so when I'm opened the file, then I got this result. So when I replaced the xls format with xlsx, everything started perfectly. And that was the reason, why is this worked when I writed it to a file, because i named it correctly. 
Thanks for the help!

**Comment by abhishekFullerlife** [comment]
Hi,
Can you please tell me how exactly you solved this issue?
