### ISSUE TITLE
IIS Compatibility - Log - file_put_contents("php://stderr" ...

### ISSUE THREAD

**Issue by matz0rz** [mk-j/PHP_XLSXWriter#155]
Hi, 

The log function is throwing a warning on IIS. 

`public static function log($string)
	{
		file_put_contents("php://stderr", date("Y-m-d H:i:s:").rtrim(is_array($string) ? json_encode($string) : $string)."\n");
	}`

> Warning:  file_put_contents(): Only 0 of 128 bytes written, possibly out of free disk space in xlsxwriter.class.php on line 663 

The above warning is being written to the generated XLSX file resulting in a corrupted spread sheet.

I suggest using error_log($string); 

Thank you for fixing!

**Comment by mk-j** [comment]
Good find.  I'll try to get to this when i get time.

**Comment by matz0rz** [comment]
Thanks, great Lib, BTW. Keep up the good work!
