### ISSUE TITLE
How tow achieve a line break in a cell?

### ISSUE THREAD

**Issue by LiLiKiLL** [mk-j/PHP_XLSXWriter#162]
NOT word-wrap when a string is too long and make the words to show. But how to achieve line break function like the <br> or "\r\n" do. Also can be done in excel with ALT + ENTER or F2 shortcut key. I haven't seached any answers for this question.

**Comment by mk-j** [comment]
In examples/ex08-advanced.php there is an example with 'wrap_text'=>true

**Comment by LiLiKiLL** [comment]
Thanks, I have read this issue [Enable line wrap and create using formula #114](https://github.com/mk-j/PHP_XLSXWriter/issues/114) of the same question.
