### ISSUE TITLE
Formating By Column

### ISSUE THREAD

**Issue by mcpalmer1328** [mk-j/PHP_XLSXWriter#163]
I would like to format only 1 column with a background color and text color 
i used this to format the column widths but i cant get it to work for more information
$col_options=array('widths'=> array(15, 20,40),  'halign'=>'center');
$writer->writeSheetHeader('PO', $header, $col_options);

i tried $col_options=array('widths'=> array(15, 20,40),  'halign'=>'center', 'fill'=>array('#fff','#fff','#fff','#fff','#fff','#eee')); but that changed nothing

i also tried 'fill'='#fff',''fill'='#fff','fill'='#fff','fill'='#fff'',fill'='#eee',  but that changed all the columns and only in the head.

thanks for the assistance

**Comment by daintycode** [comment]
Header isn't about styling. At least *actually* not.
E.g. Try this to style the 3rd column in a row:
```
$writer->writeSheetRow('PO', array(15, 20, 40), array(
    2 => array(
        'fill' => '#eee'
     )
))
```
