### ISSUE TITLE
Height doesn't work when formatting individual cells

### ISSUE THREAD

**Issue by carlosmisse** [mk-j/PHP_XLSXWriter#164]
Here's a simple example:

$styles1 = array(['height'=>100,'fill'=>'#ffc'],['height'=>100,'fill'=>'#fcf']);
$styles2 = array('height'=>100,'fill'=>'#ff0');
$writer->writeSheetRow('test', $rowdata = array('value1','value2'), $styles1);
$writer->writeSheetRow('test', $rowdata = array('value1','value2'), $styles2);

Height only works on row #2 

![sem titulo](https://user-images.githubusercontent.com/34511425/33940628-ddb1579a-dff6-11e7-9115-95e2d01eb874.png)

**Comment by mk-j** [comment]
Thanks for bringing this up.  I'll have to look into it when i get more time.

**Comment by pedro11110110100** [comment]
"height" is a style for a whole row. 
This should work:

$styles1 = array(['fill'=>'#ffc'],['height'=>100,'fill'=>'#fcf']);
$styles2 = array('height'=>100,'fill'=>'#ff0');
$writer->writeSheetRow('test', $rowdata = array('value1','value2'), array('height'=>100, $styles1));
$writer->writeSheetRow('test', $rowdata = array('value1','value2'), $styles2);
