### ISSUE TITLE
Make date datatype work with other formats than YYYY-MM-DD

### ISSUE THREAD

**Issue by nitwhiz** [mk-j/PHP_XLSXWriter#165]
Everything else than `string` will be corrected by Excel 2016.
And a specific format like `DD.MM.YYYY` on dates works, but ends up with `00.01.1900`.

**Comment by daintycode** [comment]
Problem found, it only accepts the *weird* format.

**Comment by mk-j** [comment]
Hopefully looking at `examples/ex02-formats.php` resolves this.
In that example, the date in php is '2018-12-31 23:59:59', but with the format set to DD.MM.YYYY viewing the spreadsheet display it as '12.31.2018'
