### ISSUE TITLE
how to link a sheet column to a cell as drop down list

### ISSUE THREAD

**Issue by Muzamel** [mk-j/PHP_XLSXWriter#167]
I am using this library for xls creation. How can i link a sheet column to a drop down cell. 
I have created a drop down in xls but how can i get sheet column like whole A column in drop down for drop down values. 
In excel i have done this manually when i link a sheet column to any cell its making formula like this

`=DropdownSheet!$A:$A`

**DropdonSheet** is a sheet name A is a column that i am linking

I have build a sheet using this library exactly i have done in excel DropdonSheet when i write this formula in the code to populate dropdown

`=DropdownSheet!$A:$A`  or  `=DropdownSheet!$A2:$A10`

Could you help?

Thanks in advance!

here is my **StackOverflow** question's link: https://stackoverflow.com/q/47923459/4928061

**Comment by Muzamel** [comment]
@mk-j Can you please help on this posted issue.

**Comment by loan-dev** [comment]
@mk-j Up please :) Thx

**Comment by mk-j** [comment]
Formulas are supported.
