### ISSUE TITLE
How to save the generated file?

### ISSUE THREAD

**Issue by Gonzalo2683** [mk-j/PHP_XLSXWriter#168]
I used the example ex00-simple.php but `$ writer->writeToFile('xlsx-simple.xlsx');` do not download the file, is there something missing that I can download?

Thank you

**Comment by DavidNorena** [comment]
that writes the file into the this, you need to stream it if you want to download it

**Comment by DavidNorena** [comment]
sure almost the same as mi code ! AWESOME ... I think you have your issue resolved, and you should close this issue! Have nice day !
