### ISSUE TITLE
Decimals starting with 0 formatted as text.

### ISSUE THREAD

**Issue by dciotoli** [mk-j/PHP_XLSXWriter#174]
I specified the column format as '0.00', and it seems to format all numbers correctly except numbers with a leading zero (between -1 and 1), which it formats as text. Anyone else run into this?

**Comment by mk-j** [comment]
Looks like its getting caught on the regex.... `preg_match("/^\-?[1-9][0-9]*(\.[0-9]+)?$/", $value)`

**Comment by dciotoli** [comment]
For my purposes, changing the regex to /^\-?[0-9]+(\.[0-9]+)?$/ will work. thanks!
