### ISSUE TITLE
How Can I add mathematical functions ?

### ISSUE THREAD

**Issue by bhaskarGit12345** [mk-j/PHP_XLSXWriter#182]
How can i add mathematical function like "=SUM(B3:B9)".

**Comment by bartmika** [comment]
+1

**Comment by Yursksf1** [comment]
I tried that functionality and it works,
you can try it with the first example [examples/ex01-multiple-sheets.php](https://github.com/mk-j/PHP_XLSXWriter/blob/master/examples/ex01-multiple-sheets.php) and modify the integer data and adding the formula  - look this picture



![image](https://user-images.githubusercontent.com/25001142/38682792-9979535e-3e31-11e8-9f34-0c53cb322d6d.png)
