### ISSUE TITLE
Uncaught Error: Class 'ZipArchive' not found

### ISSUE THREAD

**Issue by alvarozz** [mk-j/PHP_XLSXWriter#183]
the class ZipArchive 

XLSXWriter->writeToFile('xlsx-simple.xls...') #1 {main} .....  on line 95

the zip file is incomplete?!?

bye

**Comment by mk-j** [comment]
http://php.net/manual/en/class.ziparchive.php
is listed as:
(PHP 5 >= 5.2.0, PHP 7, PECL zip >= 1.1.0)

But for some reason, your installation of php doesn't have the php-zip package.  Are you able to install it? try `print_r(class_exists('ZipArchive'))`
