### ISSUE TITLE
simple function writeToBrowser

### ISSUE THREAD

**Issue by Bargoor** [mk-j/PHP_XLSXWriter#187]
You can add this to XLSXWriter if you want

	public function writeToBrowser($filename){
	
		header('Content-disposition: attachment; filename='.$filename);
		header('Content-type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
		header('Content-Transfer-Encoding: binary');
		header('Cache-Control: must-revalidate');
		header('Pragma: public');
		
		$this->writeToStdOut();
	}

**Comment by mk-j** [comment]
Thanks for your interest in XLSXWriter and for your suggestion.  We already have something like this in `example.php` for demonstration purposes.  We are not currently planning on adding something like "writetoBrowser()" into the library at this time.

But if you want to at this to your own library without touching the XLSXWriter... you can wrap it/extend it like this:
```
class Bargoor_XLSXWriter extends XLSXWriter
{
    public function writeToBrowser($filename){
        //...
    }
}
$writer = new Bargoor_XLSXWriter();
//...
```
