### ISSUE TITLE
Issue: numeric strings (zip codes and phone numbers) not handled well

### ISSUE THREAD

**Issue by seattledeveloper** [mk-j/PHP_XLSXWriter#19]
Hello again,

Here's a new issue I uncovered today in testing for a client. Phone numbers and zip codes often have their leading zeros removed or display as a number (1.23E+15).  I added the middle to lines of code following line 234 (I am including the line before and after to the 2 lines I added):

```
        $file->write('<c r="'.$cell.'" s="'.$s.'" t="n"><v>'.($value*1).'</v></c>');//int,float, etc
    } elseif ($cell_format=='string'){
        $file->write('<c r="'.$cell.'" s="'.$s.'" t="s"><v>'.self::xmlspecialchars($this->setSharedString($value)).'</v></c>');//string
    } elseif ($value{0}!='0' && ctype_digit($value)){ //excel wants to trim leading zeros
```

This appears to have the desired affect of having Excel read these as strings irregardless of the cell content.

Thoughts?

Ed

**Comment by mk-j** [comment]
This should be fixed properly in the latest version 0.30
