### ISSUE TITLE
Error on PHP < 5.4 because of ENT_XML1 constant

### ISSUE THREAD

**Issue by josepanguera** [mk-j/PHP_XLSXWriter#194]
In the function `xmlspecialchars` there is this line

    htmlspecialchars($val, ENT_QUOTES | ENT_XML1)

but the constant `ENT_XML1` was not [introduced until version 5.4](http://php.net/manual/en/function.htmlspecialchars.php#refsect1-function.htmlspecialchars-changelog)

**Comment by arochereau** [comment]
yup confirming,  PHPCS with CodeCompatibility sees it as well:
FILE: ...repo\licenseReporting\vendor\PHP_XLSXWriter\xlsxwriter.class.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 760 | ERROR | The constant "ENT_XML1" is not present in PHP version
     |       | 5.3 or earlier
----------------------------------------------------------------------

**Comment by cho-ko** [comment]
public static function xmlspecialchars($val)
	{
		//note, badchars does not include \t\n\r (\x09\x0a\x0d)
		static $badchars = "\x00\x01\x02\x03\x04\x05\x06\x07\x08\x0b\x0c\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f\x7f";
		static $goodchars = "                              ";
                
		// -- Start edit
		// file: xlsxwriter.class.php str: 755

		$xml_char = array(
			'"' => "&quot;",
			'&' => "&amp;",
			"'" => "&apos;",
			'<' => "&lt;",
			'>' => "&gt;",
		);
		
		$val_split = str_split($val);
		
		foreach ($val_split as $key => $value) {
			foreach ($xml_char as $sym => $change) {
				if ($value == $sym) {
					$val_split[$key] = $change;
		
					break;
				}
			}
		}
		$val = implode("", $val_split);
		unset($val_split);

		return strtr($val, $badchars, $goodchars);//strtr appears to be faster than str_replace
		// -- End edit
	}

What about this? It works for me

**Comment by mk-j** [comment]
This will be handled in a future release, in a way so as not to slow performance on every xmlspecialchars call.
