### ISSUE TITLE
Header with color

### ISSUE THREAD

**Issue by boedyirh** [mk-j/PHP_XLSXWriter#198]
I am trying to figure out how to make my header colored, but couldnot find how.
Or, I think for simplicity, that writesheetheader function has default color value (brown or something) to make it clear that it is a header;

**Comment by TheButor** [comment]
Hi,

You can just define a style, and apply it when using WriteSheetHeader:

$header_style = array('widths'=>array(10,10,30,10,10,10,10,4,10,3,10,10,10),'font'=>'Arial','font-size'=>10, 'wrap_text'=>true, 'border'=>'left,right,top,bottom','border-style'=>'medium', 'border-color'=>'#4A8C42', 'valign'=>'top', 'color'=>'#FFFFFF', 'fill'=>'#4A8C42'); 

$writer->writeSheetHeader($sheet_name, $header, $header_style);

Where 'color' is the font color, and 'fill' is the background color.

Hope it will be helpfull.

Kind Regards
