### ISSUE TITLE
Warning: ZipArchive::close(): Failure to create temporary file: Permission denied in...

### ISSUE THREAD

**Issue by youngda** [mk-j/PHP_XLSXWriter#200]
Warning: ZipArchive::close(): Failure to create temporary file: Permission denied in /xxxxxxxxxxx/vendor/mk-j/php_xlsxwriter/xlsxwriter.class.php on line 116

**Comment by youngda** [comment]
chmod -R 777 you's content

**Comment by anaselbahrawy** [comment]
Thanks
