### ISSUE TITLE
Can not read file by XLSX reader.

### ISSUE THREAD

**Issue by miten5** [mk-j/PHP_XLSXWriter#201]
Hello,

I am generate xlxs file using PHP_XLSXWriter and it generate file properly but when i upload that generated file on server, server can not read that file.

can you help me to Figure out this problem?

Thanks.

**Comment by jikker** [comment]
+1, I has some situation...

**Comment by lcelxn807** [comment]
I have same problem.
I use Laravel Excel to read the excel file.

**Comment by mrmonteith** [comment]
I haven't used it much but get the general theory and know XML.  Have you looked at the file in notepad to make sure it has all the proper begin and end tags, etc?   My guess though there are tags those programs don't like or interpret wrong.

**Comment by jikker** [comment]
I check the XML file, everyone tag has the end tag. Not this problem.
The file can correct open by excel, but it can not open by other xlsx reader.

**Comment by kananathakowsikdz** [comment]
Ya cannot read and update the xlsx. Can any one help me please?
