### ISSUE TITLE
PRINT Setup_Landscape orientation & row to repeat at top

### ISSUE THREAD

**Issue by TheButor** [mk-j/PHP_XLSXWriter#204]
Hi,

When setting the 'orientation' for printing (portrait or landscape) directly into the xlsxwriter class, the lanscape option is not applied.

Other thing,
Is the 'Row to repeat at top' possible with this class.
When printing a big array, the table header can't be repeated.

Thanks by advance for helpers.

Regards

**Comment by hnx8** [comment]
PHP_XLSXWriter(0.37) can not specify print settings(orientation, print_titles, etc.).
I also wanted to customize the print settings, so I enhanced it.
please try #207 PageSetup Support
