### ISSUE TITLE
Strip equal sign when inserting formulas

### ISSUE THREAD

**Issue by stoppeye** [mk-j/PHP_XLSXWriter#213]
The equal sign should be stripped when inserting a formula into &lt;f&gt; tags (see [Reference](https://msdn.microsoft.com/en-us/library/office/documentformat.openxml.spreadsheet.cellformula.aspx)).

While Excel will still handle it correctly, it can cause errors in other applications (e.g. Google Sheets).

Adding ltrim on the value can fix this:

    } elseif (is_string($value) && $value{0}=='='){
        $file->write('<c r="'.$cell_name.'" s="'.$cell_style_idx.'" t="s"><f>'.self::xmlspecialchars(ltrim($value, '=')).'</f></c>');

**Comment by mk-j** [comment]
fixed in https://github.com/mk-j/PHP_XLSXWriter/pull/321
