### ISSUE TITLE
Create multiple tables within one sheet

### ISSUE THREAD

**Issue by lordterrin** [mk-j/PHP_XLSXWriter#215]
First off - I've been using PHP_XLSXWriter for years and I absolutely love it.  Thank you so much! 

I've read through all of the documentation and cannot seem to find any way to create two separate tables within one spreadsheet.

I need to make a first table, with some "summary" information, then a second table 5 rows after the summary table ends, with more rows.  Is this possible?

**Comment by mk-j** [comment]
`$writer->writeSheetHeader('Sheet1', $header1);
$writer->writeSheetRow('Sheet1', $row1 );
$writer->writeSheetHeader('Sheet1', $header2);
$writer->writeSheetRow('Sheet1', $row2);` This should be possible now.
