### ISSUE TITLE
Column auto width

### ISSUE THREAD

**Issue by xMlex** [mk-j/PHP_XLSXWriter#220]
Hi! Exist this option?

**Comment by BrutusBossNL** [comment]
Also want to know badly if this will be an option in the mere future

**Comment by tgice** [comment]
Another vote for this feature.  I like to provide this along with a frozen header row for my XLSX by default.

**Comment by scorninpc** [comment]
I tried to search for the commits from May 31, 2023 but I didn't find anything. Could someone point me to the solution marked as complete?

**Comment by nguyenk** [comment]
Hi @mk-j I'd looooove to have this feature too, can you please add an example ?
