### ISSUE TITLE
write file use long time

### ISSUE THREAD

**Issue by hhxiaohei** [mk-j/PHP_XLSXWriter#223]
100K rows ,file is 2.5M,write use more than 1min

**Comment by akindemirci** [comment]
I also have the same issue. writeToStdOut() function takes a very long time. How did you solve the issue?
Thanks.

**Comment by mk-j** [comment]
Lets consider for a minute one of our examples....
`examples/ex05-numbers-250k-rows.php`

There are 3 things that can take time... 
1: generating the random numbers to use as data
answer: its just an example... random numbers take time, but real world cases won't have this

2: writing cells out as xml 
answer: not much we can do about this

3: compressing the xml files as a zip file
answer: the xlsx format is just a zip file renamed to xlsx.  If you are okay with larger file sizes... and are running php7, you can look at using [PHP.Net - setCompressionIndex](http://php.net/manual/en/ziparchive.setcompressionindex.php).  So you would modify the part of xlsxwriter that makes the the zip file, and use setCompressionIndex to set the compression to 0, which is "no compression at all" which is faster, but produces a much larger output file.

**Comment by akindemirci** [comment]
Thanks for the detailed response. I'm convinced it's not an issue.
I stretched the php.ini max_execution_time to get around it.
