### ISSUE TITLE
Formulas Excel

### ISSUE THREAD

**Issue by midall** [mk-j/PHP_XLSXWriter#23]
Hello there! Thanks for the library!

I am trying to write a formula into excel that it isnt excel formula but it is external formula. The output is empty. 

The formula is like this "=ASD("SN@CBBT corp";"AVG";" INTERVAL=1m";)"

**Comment by midall** [comment]
I found the the error is causing by semicolon ";" inside the formula. Could you help?


Thanks in advance!

**Comment by mk-j** [comment]
Thanks I'll try to look into it when I can.

**Comment by mk-j** [comment]
Can you try replacing your semi-colons with commas in the formula, let me know if that solves your issue.
