### ISSUE TITLE
Warning: fopen() [function.fopen]: Filename cannot be empty

### ISSUE THREAD

**Issue by GosseWijbenga** [mk-j/PHP_XLSXWriter#24]
Hi,

I really like your library, since it's simple and very quick!

Last couple of days I've been banging my head regarding an issue I have.
In a WAMP installation on my pc I've created a database and put some data into it. I've created a php script that uses your library to export the contents of the db to an Excel file. On my pc this is working perfectly!
Now I have transferred the database and it's contents to my webhosting provider and uploaded the php script. It now looks exactly the same as my home setup.
Yet, when I fire up the script, I receive a corrupt Excel file. If I rename the extension to html, then it contains following errors:

Warning: fopen() [function.fopen]: Filename cannot be empty in /public/sites/....mysite .../admin/xlsxwriter.class.php on line 540

Warning: str_repeat() [function.str-repeat]: Second argument has to be greater than or equal to 0 in /public/sites/....mysite ../netwerk/admin/xlsxwriter.class.php on line 201

I transferred the same to another test environment and there it's working correct!

I have no clue how to trace this issue further, so I would appreciate it very much if you could help me out here.

Thanks already!

Regards,

Gosse

**Comment by mk-j** [comment]
The library uses sys_get_temp_dir() and tempnam() to write temporary files, and then later assemble them into an .xlsx file.  Perhaps one of these functions was disabled via in your hosting provider's php.ini:
http://php.net/manual/en/ini.core.php#ini.disable-functions
```php
<?php
echo sys_get_temp_dir()."\n";
echo tempnam(sys_get_temp_dir(), "xlsx_writer_");
```

**Comment by GosseWijbenga** [comment]
Bingo!

Done it at my (Windows) pc: C:\Windows\TEMP C:\Windows\Temp\xls124F.tmp

and at my hosted (Linux) site: /tmp
The temporary file isn't created. In fact the temp_dir shouldn't be "/tmp", but /public//tmp". I hardcoded that in line 45: $filename = tempnam("/public/tmp", "xlsx_writer_");
and now it works!

Thanks a lot, you saved my day!

Regards,

Gosse

**Comment by GosseWijbenga** [comment]
What also works for me is changing line 45 to:
$filename = tempnam(ini_get('session.save_path'), "xlsx_writer_");
