### ISSUE TITLE
500 internal server error in server

### ISSUE THREAD

**Issue by bhaskarkv** [mk-j/PHP_XLSXWriter#244]
Working fine in local and when i moved the code to godaddy server i am getting HTTP ERROR 500.

**Comment by mk-j** [comment]
You'll need to do more debugging.  When I just ran it on a new server the other day, I had to install the dependency packages php-zip and php-mbstring.  If you don't have the dependencies installed it would definitely give a fatal error, like a HTTP Error 500.
