### ISSUE TITLE
Cell references in lowercase

### ISSUE THREAD

**Issue by TristanPapillon** [mk-j/PHP_XLSXWriter#25]
Hello,
I have problems with cell references because the formula is partially lowercase.

In my PHP code
```
=COUNTIF(Valeurs.B1:Valeurs.B65000;INDIRECT("A" & ROW()))
```

In the generated file
```
=COUNTIF(valeurs.b1:valeurs.b65000;INDIRECT("A" & ROW()))
```

In the file, I need to change the formula and press enter to get the right formula with capitals letters where they are needed.

Do you have any idea? Thanks for your help.

**Comment by TristanPapillon** [comment]
I think the problem is different. When I put any formula , I get an error 508, although my formula is good.

**Comment by mk-j** [comment]
I'm not sure formulas work well with semi-colons in this library.  Have you tried commas?
