### ISSUE TITLE
Add support for date parsing "DD/MM/YYYY" input date

### ISSUE THREAD

**Issue by samsong** [mk-j/PHP_XLSXWriter#259]
Please add support for date parse of "DD/MM/YYYY" to function: convert_date_time()
I wrote the code for you but can you please merge it into your codebase.

		**#*samsong* 21/1/20 - add NZ/UK style date DD/MM/YYYY
		if (preg_match("/(\d{2})\/(\d{2})\/(\d{4})/", $date_time, $matches))
		{
			list($junk,$day,$month,$year) = $matches;
		}**

**Comment by mk-j** [comment]
Because MM/DD/YYYY and DD/MM/YYYY are sometimes ambiguous, it doesn't make any sense to add either one.  What you want to do is pass your dates in as YYYY-MM-DD and then display them to the user as DD/MM/YYYY see examples/ex02-formats.php

**Comment by samsong** [comment]
Understand and agree but the problem is usually we are retrieving data from a database and it comes in a certain format. example DD/MM/YYYY. What about an alternative then so we can specify the format in the header string as "DD/MM/YYYY" and then the class will parse in that format. This way it is explicit and no room for error as your example without forcing users to manipulate and change the data before supplying.

**Comment by mk-j** [comment]
If you want it to support DD/MM/YYYY your way, thats totally fine for you to apply that patch to your own copy of PHP_XLSX_Writer.  But there are no plans to add this feature at this time.
