### ISSUE TITLE
Euro instead dollar

### ISSUE THREAD

**Issue by icyz** [mk-j/PHP_XLSXWriter#26]
Can I use euro, instead dollar? thanks

**Comment by mk-j** [comment]
Thanks for bringing that up.  I have been meaning to add other currencies
for a while.  I'll try to get tot his when I can.

**Comment by mk-j** [comment]
Try out this branch which supports custom formats
https://github.com/mk-j/PHP_XLSXWriter/tree/cell_formats
```
$header = array(
  'c1'=>'dollar',
  'c2'=>'euro',
  'c3'=>'#,##0.00', //custom
  'c4'=>'#,##0.00 [$€-407]', //german euro
  'c5'=>'[$￥-411]#,##0;[RED]-[$￥-411]#,##0', //japanese yen
);
$row = array(100,200,300,400,500);
$writer = new XLSXWriter();
$writer->writeSheet(array($row),'Sheet1', $header);
$writer->writeToFile('example.xlsx');
```

Let me know if this works for you.
