### ISSUE TITLE
@unlink( $temp_file ); fails on windows permission denied

### ISSUE THREAD

**Issue by samsong** [mk-j/PHP_XLSXWriter#260]
Not sure if it's related to my php server running on windows or on a portable drive.
Regardless in my server:

unlink temp files fails when trying to unlink temp file stored in windows temp folder AND also in a htdocs webfolder.

The error was not supressed and it was pointless anyway so I personally chose to disable the cleanup unless the user sets a temp directory.

php/apache server should cleanup their own temp files and it seems we can't get permission to delete them otherwise in some situation of windows

**Comment by 1988chg** [comment]
you should run your apache or nginx as administrator， then your php can write or remove file on your windows system。
