### ISSUE TITLE
Long number is rounded

### ISSUE THREAD

**Issue by jimmycdinata** [mk-j/PHP_XLSXWriter#27]
I had long number 3273222508910005, but it'll be written:

3.27322250891E+015

and displayed as: 3273222508910000

**Comment by mk-j** [comment]
I think I have a fix for this, its only happening on 64 bit systems because of the way filter_var($someVariable, FILTER_VALIDATE_INT) works.

**Comment by mk-j** [comment]
I tweaked a branch which should fix this, let me know if it fixes it for you:
https://github.com/mk-j/PHP_XLSXWriter/tree/cell_formats

**Comment by mk-j** [comment]
I just merged the new branch in, let me know if updating solve this.  If I don't hear from you I'll assume so and close this.
