### ISSUE TITLE
Incompatible to PHP 5.2.1

### ISSUE THREAD

**Issue by breti** [mk-j/PHP_XLSXWriter#278]
Incompatible to PHP 5.2.1 because ?: is used without the middle part. That's available with PHP 5.3+:

https://www.php.net/manual/en/language.operators.comparison.php

"The expression (expr1) ? (expr2) : (expr3) evaluates to expr2 if expr1 evaluates to TRUE, and expr3 if expr1 evaluates to FALSE.

Since PHP 5.3, it is possible to leave out the middle part of the ternary operator. Expression expr1 ?: expr3 returns expr1 if expr1 evaluates to TRUE, and expr3 otherwise. "

**Comment by mk-j** [comment]
okay this is fixed in master now.

**Comment by breti** [comment]
Thanks!
