### ISSUE TITLE
Phone numbers with leading + are interpreted as integer

### ISSUE THREAD

**Issue by nuggie** [mk-j/PHP_XLSXWriter#28]
Hi,

Phone numbers starting with + (e.g. +12345678) are interpreted as integer when the value is smaller than 32bit INT. 

I think a fix could be changing:

elseif ($value{0}!='0' && filter_var($value, FILTER_VALIDATE_INT)){ //excel wants to trim leading zeros

to

elseif ($value{0}!='0' && $value{0} != '+' && filter_var($value, FILTER_VALIDATE_INT)){ //excel wants to trim leading zeros

Greetings

**Comment by mk-j** [comment]
This is a great find, I didn't know FILTER_VALIDATE_INT allowed the plus
character.  I have a new branch in beta,
https://github.com/mk-j/PHP_XLSXWriter/tree/cell_formats made the fix in
that branch, hopefully that will have solved the issue for you.

**Comment by nuggie** [comment]
Hi,

thanks for your fix.

FILTER_VALIDATE_INT is true, because -50 and +50 are both valid INT.

Therefore you must be aware of the following problem:
Maybe someone wants negative INT values or INT values with a leading "+".
A better fix would be introducing a new class "string_numbers" in which the cell is not converted to "n".

**Comment by mk-j** [comment]
There is a new update allowing for excel or openoffice format strings like:
'GENERAL'
'#,##0.00'
'0'
'[$￥-411]#,##0;[RED]-[$￥-411]#,##0'

I'm not sure if that helps, maybe I'll have to take a look at removing FILTER_VALIDATE_INT somehow, I just don't want to have a regex in there or something that would slow down the write time of each cell significantly.

**Comment by mk-j** [comment]
Maybe now that the new cell formatting exists, i can just remove this line all together
```php
	} else if ($value{0}!='0' && $value{0}!='+' && filter_var($value, FILTER_VALIDATE_INT, array('options'=>array('max_range'=>2147483647)))){ 
			$file->write('<c r="'.$cell_name.'" s="'.$cell_format_index.'" t="n"><v>'.($value*1).'</v></c>');
```
