### ISSUE TITLE
Reference to other sheet not working

### ISSUE THREAD

**Issue by romain-le-mercier** [mk-j/PHP_XLSXWriter#289]
I know the issues are not taking under consideration, it's too bad this project could build up and be really useful.

So anyway, i'll post this here.

When writing data to display cell value from an other sheet the cell is displayed as an error at first, but when I edit the cell in excel and just press enter (without changing the formula) the value is displayed correctly.
As if an update was needed.
If anyone has a solution let me know.

**Comment by mk-j** [comment]
If you can provide a short php program which reproduces the problem, then we can reproduce it and fix it.  Otherwise there isn't enough information to reproduce and fix the reported issue.
