### ISSUE TITLE
Set header height: solution

### ISSUE THREAD

**Issue by NitemareReal** [mk-j/PHP_XLSXWriter#292]
Hello, this library is very good but have some important lacks, very, very, very easy to implement.
First lack is that I can't find any documentation about this library, just some examples, too simple and with lots of undocumented options (I had to do a lot of reverse ingeneering to find out how to use some options).

I found too that you can't give a row height for header, but solution is very very easy, you have to modify a little code to get that feature.

Locate "writeSheetHeader" function and after:

```php
if (!$suppress_row)
{
	$header_row = array_keys($header_types);
```

replace:
```php
$sheet->file_writer->write('<row collapsed="false" customFormat="false" customHeight="false" hidden="false" ht="12.1" outlineLevel="0" r="' . (1) . '">');
```
with:
```php
$ht = isset($col_options['height']) ? floatval($col_options['height']) : 12.1;
$customHt = isset($col_options['height']) ? true : false;
$sheet->file_writer->write('<row collapsed="false" customFormat="false" customHeight="'.($customHt).'" hidden="false" ht="'.($ht).'" outlineLevel="0" r="' . (1) . '">');
```

That's all!! so simple!! you can set header height.

I have found too much lacks that are too simple to implement... it's unbelievable

**Comment by uhlyarikp** [comment]
Great, thx!

**Comment by NitemareReal** [comment]
Hello, to increase compatibility (Excel 2007), change:
```php
$customHt = isset($col_options['height']) ? true : false;
```
with:
```php
$customHt = isset($col_options['height']) ? "true" : "false";
```
