### ISSUE TITLE
autoFilter

### ISSUE THREAD

**Issue by okatse** [mk-j/PHP_XLSXWriter#293]
Can you change auto filter support. 
![image](https://user-images.githubusercontent.com/72726526/95711495-2a8b4d00-0c63-11eb-8138-3918edf49cad.png)

**Comment by NitemareReal** [comment]
Hello, I have added your change to my fork from @lacopoMelani xlsWriterPlus fork. This is my xlsWriterPlus fork:

https://gist.github.com/NitemareReal/c4274f62c9239f64b3a18a7d07f7d118

(@lacopoMelani xlsWriterPlus adds suport to insert images on sheets)
