### ISSUE TITLE
Composer can only update to version 0.37 when latest is 0.38

### ISSUE THREAD

**Issue by feelkiller** [mk-j/PHP_XLSXWriter#295]
Composer can only update to version 0.37 when latest is 0.38

**Comment by slaFFik** [comment]
I can't confirm this. I've installed 0.38 using composer and got 0.38.

**Comment by IgorCode** [comment]
What version of composer?

**Comment by slaFFik** [comment]
I used Composer v2, but it doesn't matter, because both v1 and v2 are using https://packagist.org/packages/mk-j/php_xlsxwriter to retrieve the latest version.

I think this issue can be closed as `worksforme` or similar.
