### ISSUE TITLE
Support For Hyperlink without using =HYPERLINK() function

### ISSUE THREAD

**Issue by isshiren** [mk-j/PHP_XLSXWriter#298]
Hello,

When are you thinking to provide support for hyperlink function. Because when use =HYPERLINK function and export. It's working fine but when we import same file we need to remove HYPERLINK function from cell.

Please provide support as soon as possible.

**Comment by mk-j** [comment]
This is an open source project.  You are welcome to provide support for this feature whenever you have free time to do so.
