### ISSUE TITLE
Worksheet limited to 3000 lines

### ISSUE THREAD

**Issue by Entretoize** [mk-j/PHP_XLSXWriter#306]
I'm using Xlsxwriter from several years and for the first time I need more than 3000 rows in a sheet but the class doesn't seem to write more.
I'm doing:

```
$writer = new XLSXWriter();
$writer->writeSheetHeader($sheetname, $header, ['fill'=>'#2a9a9c']);
$writer->writeSheetRow($sheetname,$vals,['fill'=>"$color"]);
...
$writer->writeToFile($filepath);
```

I though about a memory limit but why 3000 rows each time and why php just stop throwing an error before writeToFile is called ?
I tried to split into 2 sheets but it writes until the total reaches  3000 lines.

**Comment by ebta** [comment]
I'm also using it and doesn't has problem with more than 3000 rows.. I can create more than 20.000 rows without problem, maybe incraese your php memory limit ?

**Comment by Entretoize** [comment]
You're true, I found that that was the php post limit. Thank you.
