### ISSUE TITLE
 PHP Notice: tempnam()

### ISSUE THREAD

**Issue by Krezalis** [mk-j/PHP_XLSXWriter#316]
Hi, php 7 i receive in log notice:

PHP Notice:  tempnam(): file created in the system's temporary directory in /var/www/______/www/vendor/mk-j/php_xlsxwriter/xlsxwriter.class.php on line 59

**Comment by sayid** [comment]
您好，我已经收到您的信件，将尽快回复您。

**Comment by ebta** [comment]
> Hi, php 7 i receive in log notice:
> 
> PHP Notice: tempnam(): file created in the system's temporary directory in /var/www/______/www/vendor/mk-j/php_xlsxwriter/xlsxwriter.class.php on line 59

It seem that your temporary directory does not exist or is not writable, see [tempnam](https://www.php.net/manual/en/function.tempnam.php)

**Comment by omarfarukmiah** [comment]
hi @Krezalis and @ebta ,

did you get any soluation for this issue? i am also getting this error.

**Comment by Krezalis** [comment]
> did you get any soluation for this issue? i am also getting this error.

Need to view log, maybe i change php temp directory

**Comment by omarfarukmiah** [comment]
> > did you get any soluation for this issue? i am also getting this error.
> 
> Need to view log, maybe i change php temp directory

Actually we did set our own temp file instead of system temp. and for our own path we need to use absolute path instead of relative path. Now it's working.

**Comment by wagnerfnds** [comment]
Guys, i guess the problem is your filename. Try something simple like "test.xlsx" as a parameter of writeToFile() function
