### ISSUE TITLE
How can I.. ?

### ISSUE THREAD

**Issue by geeflaxx** [mk-j/PHP_XLSXWriter#319]
Hey,
this framework is awesome!

How can I grow up the cell ? A2 is bigger than the cell 
```
  $writer->writeSheetHeader('Sheet1', $header, $styles2, $col_options = ['widths'=>[50,20,30,40,50,60], 'suppress_row'=> 1] );
doesn't work
```

How can I add '%' ? ( nice to have but not important )

how can I add strings in a cell with a newliine ? ( \n doesn't work )

thank you very much!

![grafik](https://user-images.githubusercontent.com/21129138/152585654-6283750e-5e0f-4e2e-9867-f7fc74eef3d6.png)

**Comment by ShuiPingYang** [comment]
I can help you in question 2.

```
<?php
include_once("XlsWriter.class.php");

$header = [
    'created' => 'string',
    'product_id' => 'integer',
    'quantity' => '#,##0',
    'amount' => 'price',
    'description' => 'string',
    'tax' => '[$$-1009]#,##0.00;[RED]-[$$-1009]#,##0.00',
];
$data = [
    ['2015-12-01'."\n".'sfdsdfasdad111111', 873, 1, '44.00', 'misc', '=D2*0.05'],
    ['2015-01-12', 324, 2, '88.00', 'none', '=D3*0.05'],
];

$styles1 = ['font' => 'Arial', 'font-size' => 10, 'font-style' => 'bold','wrap_text'=>true, 'fill' => '#eee', 'halign' => 'center', 'border' => 'left,right,top,bottom', 'border-style' => 'medium'];
$writer = new XLSXWriter();
$writer->writeSheetHeader('Sheet1', $header);
foreach ($data as $row)
    $writer->writeSheetRow('Sheet1', $row, $styles1);
$writer->writeToFile('example2.xlsx');

```

`'wrap_text'=>true`  matters,and also you need "\n"



my sheet are all dashed border ,how can I make it to your style ?  I hope you could help me,thx
![image](https://user-images.githubusercontent.com/22534808/177292444-f52073d5-43ca-4125-95c6-56b6127b4b7b.png)

**Comment by ShuiPingYang** [comment]
![image](https://user-images.githubusercontent.com/22534808/177293077-3bb53596-3c14-42b2-9b20-0e2034d8ed72.png)


please show me the code

**Comment by mk-j** [comment]
If this is still an issue, you can make a new ticket.
