### ISSUE TITLE
PHP 8.1 Support Issue - Passing null pararmeter deprecated 

### ISSUE THREAD

**Issue by zadro** [mk-j/PHP_XLSXWriter#324]
Please see error below:
```

Severity: 8192

Message: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated

Filename: php_xlsxwriter/xlsxwriter.class.php

Line Number: 760
```
Adding ternary to line 760 is a suggested fix:

`return strtr(htmlspecialchars($val ?: '', ENT_QUOTES | ENT_XML1), $badchars, $goodchars);//strtr appears to be faster than str_replace`

**Comment by LDAV** [comment]
... or completely avoid processing string, adding
`if(!$val) return "";`
at line 757

**Comment by sayid** [comment]
您好，我已经收到您的信件，将尽快回复您。

**Comment by lubos-h** [comment]
How about declaring the value as string?
`return strtr(htmlspecialchars((string)$val, ENT_QUOTES | ENT_XML1), $badchars, $goodchars);//strtr appears to be faster than str_replace`

**Comment by w263756314** [comment]
success

**Comment by mk-j** [comment]
fixed with `(string)$val` in a recent commit
