### ISSUE TITLE
How to set format for multiple row on same column

### ISSUE THREAD

**Issue by i-am-nikola** [mk-j/PHP_XLSXWriter#328]
Example A1 -> #,##0.00
A2 -> 0

**Comment by alebedze22** [comment]
Is there a solution?

**Comment by mk-j** [comment]
You should be able to specify multiple calls to writeSheetHeader now on the same sheet (if you use the latest from master). Maybe that will help?
$writer->writeSheetHeader($Mappe1, $header1);
$writer->writeSheetRow( $Mappe1, $data1);
$writer->writeSheetHeader($Mappe1, $header2);
$writer->writeSheetRow( $Mappe1, $data2);
