### ISSUE TITLE
How do I set the color of a cell?

### ISSUE THREAD

**Issue by lordterrin** [mk-j/PHP_XLSXWriter#33]
I absolutely love PHP_XLSXWriter, but I need to be able to set the background color of cells and I cannot figure out how to do that.  I did see that there's a fork where someone has added in this capability, but their version of `xlsxwriter.class.php` just gives me an internal server 500 error and won't run.

**Comment by mk-j** [comment]
PHP_XLSXWriter is often used to export data.  What kind of coloration pattern were you looking to achieve?  The headers all 1 background color and the data a different color?  Or did you need each column a different color?

**Comment by lordterrin** [comment]
I was hoping there was an option for me to set the background color of an individual cell - So my header row (1) could have something like A1 = RGB(255,255,255), A2 = RGB(50,50,50), etc etc....  Apart from this, man, PHP_XLSXWriter is an amazingly fast, and simple piece of work.  Thank you so much for building it!  I really, really appreciate it.

**Comment by boedyirh** [comment]
This is very fast class. I satisfied with its performance. :). if any plan adding coloration pattern in individual cell . Hope it still maintains its speed.

**Comment by sathishbe** [comment]
I tried this PHP_XLSXWriter and it works as expected. In my case, I want to format the cell like justified and bold. Can you please help me here.

**Comment by mk-j** [comment]
PHP_XLSXWriter as of verison 0.30 now supports cell styling, closing.  Checkout the new examples.
