### ISSUE TITLE
How to add cell data starting with space or more space (not trimmed)

### ISSUE THREAD

**Issue by AdeSupriyadi** [mk-j/PHP_XLSXWriter#336]
I need to add cell value with indent, then I added space before.

example:
```
$style =  ['font-size' => 9, 'font-style' => 'bold', 'halign' => 'center', 'wrap_text' => false, 'border-style' => 'thin', 'border' => 'left,right,top,bottom'];
$writer->writeSheetRow($sheet, ['           it is cell value'], $style);
```
but the result always trimmed.  ```it is cell value```
How to get result without trimmed space before text?

**Comment by mk-j** [comment]
I tested this, and I can't reproduce it.  It wasn't getting trimmed when I tried it.
