### ISSUE TITLE
Cell Width Increasing Issue

### ISSUE THREAD

**Issue by MULLAINATHAN** [mk-j/PHP_XLSXWriter#39]
Hi, I need help to increase cell width. Please support me. Thanks in advance.

**Comment by maslakoff** [comment]
Did you find the solution?

**Comment by MrDeff** [comment]
$sheet->file_writer->write(    '<col collapsed="false" hidden="false" max="1025" min="1" style="0" width="**11.5**"/>');

**Comment by nadtorious** [comment]
I see the line from MrDeff is already in the current version 

anyway to get a column to auto-resize to fit the content?

**Comment by REjO86** [comment]
Hello. Your library is really nice but I would also need to have the automatic width of the columns.

**Comment by mk-j** [comment]
I think auto-resize is out of the question, from a performance perspective, but it makes sense to add some kind of column width customization.

**Comment by pathfindercb** [comment]
Try my fork for colwidth. Working great for me #105 https://github.com/mk-j/PHP_XLSXWriter/pull/105

**Comment by mk-j** [comment]
An upcoming release/branch includes cell width options.
