### ISSUE TITLE
Composer can only update to version 0.21 when latest is 0.22

### ISSUE THREAD

**Issue by antonyakushin** [mk-j/PHP_XLSXWriter#41]
Trying all combinations of version set to "0.*" and "dev-master", the latest version composer updates to is 0.21. Let me know if I'm doing something wrong, or please update to get support for 0.22. Thanks!

**Comment by DavidBadura** [comment]
you need to update the project on packagist or add a hook for packagist so it can do it automatically

**Comment by mk-j** [comment]
It should be updated to 0.22 now.

**Comment by DavidBadura** [comment]
thank you! :)

**Comment by rps-repo** [comment]
Hi,

Here is some information on the new stuff that may seem helpful to you, read more here <http://propastehi.spiritualbusinessplan.org/aeagrf>

All best, tom@rapidach.com

**Comment by rps-repo** [comment]
Hey, Don't miss up this new stuff, you're going to be delighted, read more here <http://lonkuqualtu.centuryphotography.net/aemcbcd>

Very truly yours, tom@rapidach.com

**Comment by rps-repo** [comment]
Greetings! 

I just wanted to share  with you my excitement about some amazing stuff, just take a look at that  <http://advantage.thewonderland.in/aeacype>

Very truly yours, tom@paytracs.com

**Comment by rps-repo** [comment]
Hi friend! 

I  couldn't decide which model of  phone to  buy so I decided to ask you, please take a look <http://bridge.proitny.com/aebvlgb>

Yours truly, tom@paytracs.com
~SUBJECT=need  your advice
Hi friend! 

I've found something interesting and need your opinion about that stuff,  please take a  look <http://bridge.proitny.com/aebvlgb>

Yours truly, tom@paytracs.com

**Comment by rps-repo** [comment]
Hi friend! 

There is some stuff I wanted to  show you,  it is  just amazing, take a look <http://let.seasucker.us/aesrerf>

Thanks for your consideration, tom@paytracs.com
