### ISSUE TITLE
Quick troubleshooting - file not produced...

### ISSUE THREAD

**Issue by markmanley** [mk-j/PHP_XLSXWriter#43]
Hi - following the first example to writeToFile('output.xlsx') but can't find the file. Searched everywhere. Script is getting to that point and beyond. Anything I should look at permissions-wise or ???

Where should I expect to see the file saved?
Thanks in advance!

**Comment by mk-j** [comment]
You can do writeToFile('/tmp/output.xlsx') if you want... You should only
write to a directory your app has permissions to write to.

If you are running example-cli.php via command line php, output.xlsx will
be in the directory you are in when you run the command "php
example-cli.php" at the command prompt.

**Comment by markmanley** [comment]
Thanks - that got it!
