### ISSUE TITLE
Question sur les styles

### ISSUE THREAD

**Issue by dabraxis** [mk-j/PHP_XLSXWriter#46]
How can have add styles such as bold, italics, etc ...?

**Comment by mk-j** [comment]
I will try to get to this soon, but the quick answer is, bold and italics
are not supported yet.

-Mark

**Comment by dfoxxdfoxx** [comment]
Is this possible by now?

**Comment by mk-j** [comment]
PHP_XLSXWriter as of verison 0.30 now supports cell styling, closing.
