### ISSUE TITLE
multi-line cells support?

### ISSUE THREAD

**Issue by cpainchaud** [mk-j/PHP_XLSXWriter#47]
Hi there,

 I am not sure if your lib supports it from the different examples I read so I am asking now : is it possible to to multi-line cells with your write ? if yes, how ? 

i am attaching a screenshot of what I am looking for 
![screen shot 2015-10-11 at 16 10 46](https://cloud.githubusercontent.com/assets/6696638/10417198/c5e442de-7032-11e5-951f-70a8eb96740c.png)

thx !

**Comment by mk-j** [comment]
There is an example of merge cells,
see:
https://github.com/mk-j/PHP_XLSXWriter/blob/master/example-cli-merge-cells.php

**Comment by cpainchaud** [comment]
ok so it means I would have to create fake lines and then merge some of the columns ?

what about making it simpler like:

$row2 = array(100, 200, 300, Array( 'info1','info2', 'info3' ), 500);

so if an array member is an array, you consider it as a multi-line/merged cell .

**Comment by mk-j** [comment]
From your screenshot, you may just be able to do:
$row2 = array(100, 200, 300, "info1\ninfo2\ninfo3", 500);

I don't think you need merge cells at all for that...

**Comment by cpainchaud** [comment]
actually a \n doesnt mean a cell but just line break text which is different and I am looking multi-cells/merged cells (a bit like html padding?)

**Comment by cpainchaud** [comment]
i made a quick patch to allow Array() row members as described, are you interested ?

**Comment by mk-j** [comment]
The merge cells example is now in examples/ex07-advanced.php
