### ISSUE TITLE
Using this library without ZipArchive class

### ISSUE THREAD

**Issue by deoval** [mk-j/PHP_XLSXWriter#48]
Is there a way to use this library without ZipArchive class? For example, using PclZip class.

**Comment by mk-j** [comment]
There probably is, feel free to replace ZipArchive with PclZip class, you'd
have to change XLSXWriter::writeToFile()

**Comment by YlianEstevez** [comment]
I made quite successfully this translation. it's quite perfect. i just keep an error when opening the generated excel file (unreadeable content). When clicking yes on Excel dialog, the file is opening fine.

i can publish the alternate class if needed.
