### ISSUE TITLE
File creation / string building

### ISSUE THREAD

**Issue by martinamw** [mk-j/PHP_XLSXWriter#5]
This isn't really an issue, more of a question or idea.  I'm writing about 8000 rows, and 8 columns to a spreadsheet.  It takes about 4 seconds, which is quick in comparison to phpexcel.  Just wondering if I could speed it up, and had an idea:

Instead of it looping through the data array, and writing to a file for every cell..what if it built a string, and wrote to the file just once, at the end ?

I'm not sure if that would have any performance improvements or not ?

**Comment by mk-j** [comment]
The latest version 0.30 has memory usage of 1MB not 16MB in this case.
