### ISSUE TITLE
Error only on Linux

### ISSUE THREAD

**Issue by Perocat** [mk-j/PHP_XLSXWriter#50]
When using class PHP_XLSXWriter on Linux system I always get this error opening the file in Excel:

    Parte rimossa: Parte /xl/sharedStrings.xml con errore XML.  (Stringhe)
    (Part removed: Part /xl/sharedStrings.xml with error XML. (Strings))
    Carattere xml non valido. Riga 2, colonna 1898.
    (xml char not valid. Row 2, column 1898.)
    Record rimossi: Informazioni cella dalla parte /xl/worksheets/sheet1.xml
    (Record removed: cells informations from part /xl/worksheets/sheet1.xml)

On Windows PHP Apache no errors, no problems! I have no idea how to solve the problem...
Any help is much appreciated!!!

Thank you

**Comment by mk-j** [comment]
What characters were written to row 2 colum 1898?  If you unzip the .xlsx
file, you should be able to open
/xl/worksheets/sheet1.xml in text editor, and perhaps navigate to that row,
and column and figure out why that cell is corrupted.  Perhaps a special
character like é is UTF8 encoded in one operating system but UTF16LE in the
other.  I really couldn't say for sure.
