### ISSUE TITLE
Write by row and column

### ISSUE THREAD

**Issue by lmendoza92** [mk-j/PHP_XLSXWriter#52]
Hello everybody!

How can I write by row and column in a specific sheet ? (Excel with multiple sheets)

Is this possible ?

Thanks

**Comment by mk-j** [comment]
One of the design restrictions of the library is that it must write from top row to bottom so it can write rows directly to the spreadsheet instead of storing it all in memory first, the way typical libraries work.
```
$writer->writeSheetRow('Sheet1', array(1,2,3) );
$writer->writeSheetRow('Sheet1', array(4,5,6) );
```
