### ISSUE TITLE
Number stored as Text

### ISSUE THREAD

**Issue by dreamfalcon** [mk-j/PHP_XLSXWriter#53]
Hi,
I was getting this error on Excel, because all data coming from mysql is inside commas:
'1', '5.1'
and XLSXWriter assumed its a string.

Tried changing the column type to 'GENERAL', but same error.
Adding this to my code:
is_numeric($value) $value=trim($value,"'");
didn't work, because Excel was giving an error when opening the file.

So I changed this line in XLSXWriter:
} else if (!is_string($value)){ 
to 
} else if (!is_string($value) || is_numeric($value)){ 

and it worked :)

But is there an option without changing XLSXWriter?

Thx

**Comment by mk-j** [comment]
This should be fixed in version 0.30, it used to try to auto-detect column types, now it only does so when the column types are not specified.
