### ISSUE TITLE
tab

### ISSUE THREAD

**Issue by chatis** [mk-j/PHP_XLSXWriter#54]
You our data has chr(11), your excel while open with error... we need to change chr(11) to chr(13) to won't have any error...

I juste change your code like this :

$this->writeCell($sheet->file_writer, $sheet->row_count, $column_count, $v, $sheet->columns[$column_count]);

to

$this->writeCell($sheet->file_writer, $sheet->row_count, $column_count, str_replace(chr(11), chr(13), $v), $sheet->columns[$column_count]);

**Comment by mk-j** [comment]
This should be fixed now in version 0.30
