### ISSUE TITLE
hi insert in composer.json file required min PHP 5.2.x

### ISSUE THREAD

**Issue by EOM** [mk-j/PHP_XLSXWriter#55]
hi, insert in composer.json
required supports PHP 5.2.1+

**Comment by mk-j** [comment]
I'm not familiar with composer.json, does you put in:
    "require": {
        "php": "~5.2.1",
    }
or
    "require": {
        "php": "5.2.1",
    }
or
    "require": {
        "php": "5.2.1.*",
    }

**Comment by mayank** [comment]
@mk-j It's simple
```javascript
   "require": {
        "php": ">=5.2.1"
    }
```
For Reference https://getcomposer.org/doc/articles/versions.md#range
