### ISSUE TITLE
Error when cell value starts with "=" but it is not intended for formula

### ISSUE THREAD

**Issue by siufay325** [mk-j/PHP_XLSXWriter#57]
Can there be a setting to disable formula detection and just treat values as normal strings?

**Comment by mk-j** [comment]
I think you can force a string like this "='text", so that might also mean you can force it to be "='=text" to display a single prepended equals sign before your text.

**Comment by jeng28** [comment]
Hi, I've the same problem but I solved it by using these method.
1. add single quote in front of the equal sign
2. add single space before equal sign

Both work for me. Hope this help.
