### ISSUE TITLE
Datetime celltype not show correctly in iphone.

### ISSUE THREAD

**Issue by ac1982** [mk-j/PHP_XLSXWriter#58]
When I use datetime as the celltype, and the data like Carbon::now();
And it could be shown right in Excel 2016 (Windows version), but not in iPhone, Android and HTML5 reader. The date will be displayed like " 2016-02-58 15:45", the day is wrong absolutely.
Hope you can fix it. Thank you.

**Comment by mk-j** [comment]
You'll have to post a standalone working example of the PHP_XLSXWriter code you used to generate your spreadsheet (not the full code, but shrink it down until it only has 1 or 2 rows in it and still reproduces your issue).

**Comment by ac1982** [comment]
Really thanks for your support.
[sample.zip](https://github.com/mk-j/PHP_XLSXWriter/files/179833/sample.zip)

**Comment by mk-j** [comment]
I think if you called strval(Carbon::now()), before passing it to PHP_XLSXWriter, it would help it to force it to be a string before my library looks at it.

There is a new version of PHP_XLSXWriter which also may solve your issue.
