### ISSUE TITLE
Invalid XLSX file if using custom formatting

### ISSUE THREAD

**Issue by Hammish** [mk-j/PHP_XLSXWriter#63]
I found an issue where I'm trying to format using a custom format of "@" and a non-numeric value, but when I do it's creating an invalid XLSX file. Excel is able to repair it, but Libreoffice just replaces all invalid fields with 0. Upon inspection in the code, it looks like @ is getting detected as currency (and therefore numeric rather than a string) on line 161 due to an incorrect regex, causing the writer to insert the value directly rather than using a shared string.

I don't know how to perform a pull request, however I have a diff of the line in question that fixes the issue.

Also: to anyone having issues with Excel complaining about "We found a problem with some content" when using custom formatting, try this change and see if it fixes the issue.

[wms@wmsrdev lib]$ diff xlsxwriter.class.php xlsxwriter.class.php.fixed
161c161
               if (preg_match("/$/", $cell_format)) return 'currency';
               if (preg_match("/\\$/", $cell_format)) return 'currency';

Edit: github auto-format seems to be mangling the diff above, so FYI the top line is the original line, and the bottom line is the fixed line.

**Comment by cmanley** [comment]
As a side note: it's not efficient to use regular expressions where simple string functions can be used. In this case: strpos.

**Comment by mk-j** [comment]
This should be fixed in version 0.30.
