### ISSUE TITLE
Excel cannot open XLSX file "format for the file extension is not valid" 

### ISSUE THREAD

**Issue by WaldoTH** [mk-j/PHP_XLSXWriter#65]
Hello, I'm having trouble with this library for some weird reason. I've been able to use this without any problem in all my project, except for one of the files: in this one I always get the 'file extension is not valid' when I try to use PHP_XLSXWriter, but I'm using the exact same code as in the other files of my project (in which the library runs perfectly).
Here's the code I'm using to test:

 ini_set('display_errors', 0);
        ini_set('log_errors', 1);
        error_reporting(E_ALL & ~E_NOTICE);

```
    $filename = "example.xlsx";
    header('Content-disposition: attachment; filename="'.XLSXWriter::sanitize_filename($filename).'"');
    header("Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    header('Content-Transfer-Encoding: binary');
    header('Cache-Control: must-revalidate');
    header('Pragma: public');

    $header = array(
        'year'=>'string',
        'month'=>'string'
    );
    $data1 = array(
        array('2003','1'),
        array('2003','2'),
    );

    $writer = new XLSXWriter();
    $writer->setAuthor('Some Author');
    $writer->writeSheet($data1,'Sheet1',$header);
    $writer->writeToStdOut();
    exit(0);
```

That's it. But I always get the error message in this specific page. What could be causing this? Any clue??
 Thank you so much for your help!

**Comment by OZZlE** [comment]
I have the same issue, this lib doesn't seem to work at all. I used php version 5.6.10

**Comment by webmcheck** [comment]
Same problem. 
Looks like some trouble in ZipArchive class. If I repack file (unzip .xlsx -> zip back result to .xlsx) all works well. 
Also, I tested it on few PHP versions and only with one of them I have a problem. Unfortunately, I can't get access PHP and zip versions on that PC.

**Comment by webmcheck** [comment]
In my case, I find the problem.
All bad files start with `herePK` string. If I change it on `PK` Excel works well.

![2017-03-03 10_25_14-__c-01_shared_ _fpma_export 4 xlsx - notepad](https://cloud.githubusercontent.com/assets/1275723/23542110/60bcdeb0-fffc-11e6-9010-21a19af41cbd.png)

**Comment by mk-j** [comment]
I believe your code has something like ```echo "here";``` in it, and that is corrupting the xlsx file.

**Comment by maxrisk** [comment]
I get the same problem when I run the example.php. The file size is 0 byte. But I run examples/ex00-simple.php with CLI it worked. I don't know how to fix

**Comment by maxrisk** [comment]
I fix this problem with `$writer->setTempDir('path');`. It seem to be I don't have the permission to access the system's temporary.

**Comment by webmcheck** [comment]
@mk-j yes, you're right, my client added it in his copy for  debugging
