### ISSUE TITLE
Support for TEXT cells/columns?

### ISSUE THREAD

**Issue by michelgallant** [mk-j/PHP_XLSXWriter#68]
I was wondering if it were possible to somehow support a "TEXT" formatted cell/column?
Currently, the "GENERAL" formatting used for strings tends to allow numeric strings like "791310019801" to show up like 7.913100E+11

Thanks

**Comment by mk-j** [comment]
Have you tried writing those as "='791310019801", I think excel will honor those as text.

**Comment by mk-j** [comment]
This should be fixed now.  Previously the spreadsheet library would auto-detect cell types, causing the issue you described.  Now it only auto-detects when the header is not specified.  If you set a column to be 'string' or '@', numbers will be interpreted as strings now.
