### ISSUE TITLE
Excel 2010

### ISSUE THREAD

**Issue by chillichicken** [mk-j/PHP_XLSXWriter#7]
When opening a generated xlsx file with Excel 2010 I am prompted with "Excel found unreadable content in 'test.xlsx' Do you want to recover the contents of this workbook ? If you trust the source of this workbook, click Yes".

I am using the example provided.

$header = array(
    'year'=>'string',
    'month'=>'string',
    'amount'=>'money',
);
$data = array(
    array('2003','1','-50.5'),
    array('2003','5', '23.5'),
);

$writer = new XLSXWriter();
$writer->setAuthor('Doc Author');
$writer->writeSheet($data,'Sheet1',$header);
$writer->writeToFile('test.xlsx');

**Comment by thanhhungtn1** [comment]
I've just also faced this problem too.
I tried example and cannot open the file in Excel 2016.
Maybe there is a problem of compatibility?
