### ISSUE TITLE
Please use multibyte functions

### ISSUE THREAD

**Issue by jorunkel** [mk-j/PHP_XLSXWriter#71]
When trying to use the "euro" cell formatting it failed because in xlsxwriter.class.php on line 210:

`$cell_format = strtoupper($cell_format);`

`$cell_format` gets an empty string assigned. This can be avoided using the mb_strtoupper() equivalent:

`$cell_format = mb_strtoupper($cell_format);`

Multibyte functions should be used everywhere.

PS: Great library otherwise. Exactly what I was looking for!

**Comment by mk-j** [comment]
Thanks for submitting this, I'll try to have a look at it in the next few
days.

**Comment by javadev** [comment]
+

**Comment by mk-j** [comment]
I don't think this is an issue anymore.
