### ISSUE TITLE
Links adding feature

### ISSUE THREAD

**Issue by KielD-01** [mk-j/PHP_XLSXWriter#74]
Hi, mk-j!

I've tried to add a link with few methods, but it doesn't work.
How can i insert one ?
Cause in Sheet i have a column with link on image that should be clickable after file generating.

Thanks in advance.

**Comment by mk-j** [comment]
Someone added this:
https://github.com/mk-j/PHP_XLSXWriter/pull/66

**Comment by KielD-01** [comment]
Ya, cool :) Good job, Bro :+1:
