### ISSUE TITLE
add "Excel-Table" feature

### ISSUE THREAD

**Issue by ryrun** [mk-j/PHP_XLSXWriter#75]
Since Excel 2010 (or maybe 2008), there is a great table feature, which auto colors cells / headlines and automatically creates filter for the headlines. I've looked in a xlsx file and the table just needs to be declared separately (there are some declarations in the sheet xml and a separate table xml file). The coloring and filters will be set automatically on load and are not saved in the xlsx.

Could be a solution for #61, too.

Screenshot:
http://imgur.com/a/YTqdO

Article about this feature:
https://support.office.com/en-us/article/Overview-of-Excel-tables-7ab0bb7d-3a9e-4b56-a3c9-6c94334e492c

**Comment by mk-j** [comment]
There are no plans to add this feature at this time, but thanks for the suggestion.
