### ISSUE TITLE
Overwriting

### ISSUE THREAD

**Issue by chiel1112** [mk-j/PHP_XLSXWriter#77]
Hello,
Could you make it so it adds every new input next to the one before in the spreadsheet please?

Thanks!
Chiel

**Comment by edward1985** [comment]
I don't know what you mean. Is this mail for me?

**Comment by chiel1112** [comment]
I mean that it overwrites the past answers of my html form so if it could enter A new colum or sheet on my xlsx file. So it looks like this

Test1           Test2
Ja                No
Ja                No
Ja                No
<here Goes A file but that didn't work so i decided not to use it>
Test1           Yes

**Comment by mk-j** [comment]
This spreadsheet library is only meant for writing.  It cannot read or modify an existing spreadsheet.
