### ISSUE TITLE
Sheet name too long

### ISSUE THREAD

**Issue by BavoJanss** [mk-j/PHP_XLSXWriter#78]
When adding a sheet names over 30 characters are accepted. When opening these files in Excel it says "we found a problem with some content ... recover .. click yes", after that the workbook is repaired and the sheet-names truncated back to 30 characters.

**Comment by IulianDide** [comment]
Excel has some restrictions on the sheet's name:
it must not be blank
it must not exceed 31 characters
it must not contain these characters: \ / ? * : [ or ]
it must not start or end with a single quote
it must be unique

**Comment by mk-j** [comment]
An upcoming branch/release enforces some restrictions on the sheet name (through truncation)
