### ISSUE TITLE
How can i make the first row with headers Bold?

### ISSUE THREAD

**Issue by dfoxxdfoxx** [mk-j/PHP_XLSXWriter#80]
I am using PHP_XLSXWriter for exporting a array to a xlsx file because its very fast and much faster than PHPExcel, thank ypu for that.

But i would like only the first row with column names to be bold. I tried to change it myself by changing the $cell_format_index but than the xlsx file becomes corrupt.

I also tried the below fork but that is full of errors and an older version:

https://github.com/SystemDevil/PHP_XLSXWriter_plus

Could you please tell me how this can be done?

**Comment by mindyourstep** [comment]
Could you find a solution?

**Comment by prafful-panwar** [comment]
still looking for that. any help ? also same time i m getting this error "we found a problem with some content in xyz.xlsx"

**Comment by mk-j** [comment]
Download the new version 0.30 it not supports simple cell styling including bold.

**Comment by Buccleuch** [comment]
The cell styling only seems to work for normal rows (writeSheetRow). It doesn't seem to be possible to writeSheetHeader and also style that header.
