### ISSUE TITLE
i want to change the path for download excel something like this.

### ISSUE THREAD

**Issue by prafful-panwar** [mk-j/PHP_XLSXWriter#81]
is there any option for change the path of download excel file.
as its taking default main directory and we cant give permission of that main folder to write permission 
xlsxwriter.Workbook(filename, {'tmpdir': '/home/user/tmp'})

**Comment by prafful-panwar** [comment]
Sorry it was there .

**Comment by mk-j** [comment]
The latest version has a way of changing the tmpdir it writes to as it builds the spreadsheet.
