### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by sc0ttkclark** [mk-j/PHP_XLSXWriter#82]
Looking for a way to make the xlsx password protected, would love anyone's ideas/tips.

**Comment by mk-j** [comment]
An xlsx is just a zip file.  So if you can make a zip file password protected, you should be able to do the same to an existing xlsx file.

**Comment by fmaltez** [comment]
> Looking for a way to make the xlsx password protected, would love anyone's ideas/tips.

Use writeToString and use this NPM package to encrypt the xlsx https://github.com/nick322/secure-spreadsheet/compare/master...tperalta82:secure-spreadsheet:master (pull request pending).
