### ISSUE TITLE
Latest version can not be read / imported

### ISSUE THREAD

**Issue by dfoxxdfoxx** [mk-j/PHP_XLSXWriter#91]
When i am using the latest version the generated .xlsx file can not be read by akeneo-labs/spreadsheet-parser (for example) to import and process the file.
All the string values are left blank and only the nummeric values stay in place.

When i am using the attached older version everything works fine.
Does anyone know what is going wrong?

[xlsxwriter.class.txt](https://github.com/mk-j/PHP_XLSXWriter/files/789453/xlsxwriter.class.txt)

**Comment by mk-j** [comment]
I'm not familiar with akeneo-labs/spreadsheet-parser, but perhaps there is a bug in it?  The change that was made in the recent version of PHP_XLSXWriter was to stop using shared string, and to write all strings as inline strings.  Switching to inline strings was done on purpose to reduce memory usage when writing gigantic spreadsheets.  If the older version works fine, you should just keep using that version.

**Comment by dfoxxdfoxx** [comment]
akeneo-labs/spreadsheet-parser is a very fast xlsx and csv reader.
The strange thing is that when i save the generated xlsx file once in Excel it can be imported by akeneo-labs/spreadsheet-parser. Maybe there is something missing in PHP_XLSXWriter that gets corrected/added by Excel?

Akeneo: [https://github.com/akeneo-labs/spreadsheet-parser](https://github.com/akeneo-labs/spreadsheet-parser)

**Comment by mk-j** [comment]
No, like I said I changed PHP_XLSXWriter to use inline strings instead of the shared string index. akeneo-labs/spreadsheet-parser must not be able to parse the inline strings.  File a ticket in akeneo-labs/spreadsheet-parser, or use the old version of PHP_XLSXWriter.

**Comment by dosangminh** [comment]
I has the same issue : (

**Comment by dfoxxdfoxx** [comment]
This is fixed in a newer version of akeneo-labs/spreadsheet-parser with the pull request below:
https://github.com/akeneo-labs/spreadsheet-parser/pull/43

**Comment by mk-j** [comment]
https://github.com/mk-j/PHP_XLSXWriter/releases
PHP_XLSXWriter 0.22 used shared strings.
PHP_XLSXWriter 0.30+ uses inline strings.

Closing...
