### ISSUE TITLE
Problems with non-unique column names

### ISSUE THREAD

**Issue by stoppeye** [mk-j/PHP_XLSXWriter#92]
Since you use an associative array to define the column names and types, it is not possible to have multiple columns with the same name, which is otherwise no problem in Excel.
In my project, the user can flexibly define which columns of data should be exported into Excel (and can also re-label the column names). A typical use case in this project is, that you will get person and address data in one row. So it's not unusual that you will have identical column names, as you can have 'first name', 'last name' as part of the person data as well as the address data.

To avoid this problem, I would suggest to use an approach like this for defining the headers:

```
$header = array(
  array('created', 'date'),
  array('product_id', 'integer'),
  array('description', 'string'),
);
```
Or even more verbose:

```
$header = array(
  array('label'=>'created', 'type'=>'date'),
  array('label'=>'product_id', 'type'=>'integer'),
  array('label'=>'description', 'type'=>'string'),
);
```

**Comment by mk-j** [comment]
I understand what you are suggesting, and I realize this is a limitation of PHP_XLSXWriter, but I like the simplicity of the current way, which seems to do the trick in 99% of the time.

If someone needs duplicate column names, they can always add a space or underscore:
```
$header = array(
  'created'=>'date',
  'created_'=>'date',
  'created '=>'date',
  'created  '=>'date',
);
```
