### ISSUE TITLE
Fields starting with "="  cause an error

### ISSUE THREAD

**Issue by farhantahir** [mk-j/PHP_XLSXWriter#97]
Fields starting with "=" gives following output, "Err:520". 
I believe its trying to calculate a formula but the field is not actually a formula, it a text field, though in my case some of the users put "=" to skip mandatory field and I got this error.

**Comment by mk-j** [comment]
As you are exporting your data, scan for any of your data starting with = and prepend =' in front... 
example... if your data contains:
=BS417
Wrap your data in ="<yourdatahere>"
="=BS417"

Currently starting with = signals a formula,

**Comment by farhantahir** [comment]
@mk-j  Thanks I'll try it

**Comment by farhantahir** [comment]
@mk-j  I did it and it worked. Thanks
