### ISSUE TITLE
Please reconsider...

### ISSUE THREAD

**Issue by orbex** [mk-j/PHP_XLSXWriter#98]
As of version 0.30 there is a required-dev package xrstf/composer-php52
Please reconsider this as it is *very* old and not maintained.
More info : https://github.com/composer-php52/composer-php52

> Please do not use this, if you can avoid it. It's a horrible hack, often breaks and is extremely tied to Composer's interna. This package was originally developed in 2012, when PHP 5.2 was much more common on cheap webhosts.

On a sidenote - Webmasters still on php 5.2 should seriously consider upgrading to at least 5.6 to plug some serious security holes...

**Comment by mk-j** [comment]
Okay, try 0.32
